### ISSUE TITLE
Run Output must handle one result as well.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#102]
At the moment it is extent of layer that is returned from postgres. That is in case of one point feature it's just null geometry returned.

Expected behaviour: if one point feature found fly to it and select. If none found - alert.

**Comment by dbauszus-glx** [comment]
If none found the output should not be shown. The filter should fire a call to a route which returns the number of found items. Ideally this number should be shown.

```
123 locations
[Run Output]
```

The number should always be shown whether output is enabled or not.

**Comment by dbauszus-glx** [comment]
Run output is now disabled with <1 results.
