### ISSUE TITLE
User [API] key generation

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1036]
Currently a user [API] key can only be generated from request with a user cookie.

**Comment by RobAndrewHurst** [comment]
### Possible Requirements: 

1. Allow a user that is API enabled to generate an API key using the `api/user/key` endpoint.
2. The user can provide provide an **email address**, and can authenticate against **2FA** or an email sent to the user granting a token to the user for a window of time. (5, 10, or 15mins).
3. Once the user has verified the email or 2FA then the Token is released from the **pending request**.

**Comment by dbauszus-glx** [comment]
#1039 enables authentication with a basic `--user:email:password` [authorization header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication).
