### ISSUE TITLE
filter button doesn't work

### ISSUE THREAD

**Issue by alemcmartin** [GEOLYTIX/xyz#104]
The highlighted button doesn't dynamically filter the table results.
If you type a value in the "smaller or equal" field it filters correctly. The button doesn't do anything.

![glx_issue](https://user-images.githubusercontent.com/14032173/55157730-0b969a00-5155-11e9-9d98-057f4b6c08f7.JPG)

**Comment by cityremade** [comment]
Input spin box removed with css.
