### ISSUE TITLE
MVT layer (and possibly others) fail when '_.fields' is empty

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#1051]
An MVT layer fails when _.fields value in the get location query is empty - get location template gets an extra comma which crashes the query.
How to reproduce: add a layer in the workspace **not from template, no style object, no labels**.

```const fields = _.fields?.split(',')
    .map(field => `${_.workspace.templates[field]?.template || field} AS ${field}`)
    .filter(field => !!field)
    || []
```

`${Array.isArray(fields) ? fields.toString() + ',' : ''}`

The above line causes an unwanted comma.

**Comment by dbauszus-glx** [comment]
Can you test this against #1043 ?

**Comment by cityremade** [comment]
Done and fixed;
