### ISSUE TITLE
Select location from table view.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#108]
It should be possible to select a location by clicking on the table view record.

**Comment by dbauszus-glx** [comment]
It is now.

I only tested this with the Natural Earth dataset in dev.json

![image](https://user-images.githubusercontent.com/22201617/55495482-e31b0e00-5634-11e9-9861-fdbf9a1f8ee2.png)

**Comment by RobAndrewHurst** [comment]
Added to Documentation
