### ISSUE TITLE
Layer key in location view.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#110]
Layer keys can be arbitrary and should therefore not be shown in the info view. If the layer key should be pushed into the location view then there should be a key to enable this function.

**Comment by cityremade** [comment]
When adding an entry to infoj:
{"type": "key"} a small coloured label with layer name will be generated.
![Uploading Screenshot 2019-04-03 at 17.10.33.png…]()

**Comment by dbauszus-glx** [comment]
excellent, reopened for documentation...

**Comment by cityremade** [comment]
Added to docs.
