### ISSUE TITLE
Tableview viewports

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#112]
Currently layer tableviews will always filter for the viewport. This should be optional.

**Comment by dbauszus-glx** [comment]
Layer table have now a viewport flag. This can be toggled with a button in the tableview button column.

![image](https://user-images.githubusercontent.com/22201617/55487970-076fee00-5627-11e9-9e70-84212c6e2aa2.png)

The default is off. The layer table will not update with viewport changes since all data is shown.

This will work together with layer table sorting.

![image](https://user-images.githubusercontent.com/22201617/55488068-3dad6d80-5627-11e9-8d9e-f236df8099ce.png)

**Comment by RobAndrewHurst** [comment]
Added to documentation
