### ISSUE TITLE
Tableview with multiple selections.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#114]
When selected two features from the same layer all related tabs are opened which results in duplicate names. How about including selection index letter to the tab header?

**Comment by dbauszus-glx** [comment]
Quick and easy solution would be to make the text colour match the selection colour.

**Comment by cityremade** [comment]
Now selection colours linked to new tabs if they refer to selected location.
![Screenshot 2019-04-03 at 17 17 00](https://user-images.githubusercontent.com/7070711/55495236-5c663100-5634-11e9-918e-3f4d96f51a2d.png)
