### ISSUE TITLE
mapp.ui.layers.panels.style composition

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1154]
The style panel module creates a drawer with a legend and supporting style elements for hover and label. Changing the theme will reload the panel.

It should be possible to have the legend from the theme with the label and hover control outside the style panel.

A method to construct the style view with selected elements should be available to be called from the panel.

**Comment by dbauszus-glx** [comment]
#1362 must be merged before this can be addressed.

**Comment by simon-leech** [comment]
When using a `categorized` thematic with `fields` array - the `switch-all` text is not applied. This is correct as `switch-all` cannot work. 
However, there should be a default applied for the user. 

We need to ensure we test `theme.meta`.
