### ISSUE TITLE
SVG from github raw as symbol

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#116]
The svg_symbols util will return a url if the marker is typeof string. However in order to load a symbol it is required to add the source to the imgsrc CSP directive in the server.js.

Furthermore, SVG may contain script tags which will prevent the image to be displayed in a sane browser. In order to use images hosted on github via the github raw endpoint it is necessary to add sanitize=true as a querystring parameter to the end of the url.

```
"marker": "https://raw.githubusercontent.com/GEOLYTIX/MapIcons/master/cinema.svg?sanitize=true"
```

**Comment by cityremade** [comment]
Added to docs.
