### ISSUE TITLE
Mvt cache table

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#117]
Making the mvt_cache layer entry boolean was a brain fart.

This is now the name of the cache table.

e.g.

```
"mvt_cache": "wh.retail_place__mvts",
```

**Comment by dbauszus-glx** [comment]
Because tables maybe in a different database schema and I want to control in which schema the cache table should be generated.

Additionally there was a problem with the same table being used multiple times in the same or different deployments.

**Comment by RobAndrewHurst** [comment]
Updated documentation
