### ISSUE TITLE
_default view on mobile devices

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1269]
Issues on Mobile View: 
- Cluster selection- click on a row in the cluster pop up, nothing happens
- Dataviews - They are display none but you can still turn off/on the checkboxes that show/hide them. 
- Delete Location - Pop up to confirm doesn’t appear  [fixed in dialog changes] ✅

**Comment by RobAndrewHurst** [comment]
We can mark this as complete?

**Comment by dbauszus-glx** [comment]
No.... The growing button column needs to be addressed. Will change to RFC.

**Comment by simon-leech** [comment]
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/40a9f6f0-549e-4dfb-bd40-9ad82d4cb624)

The helpModal does not stay within the viewport of the mapview when you use mobileview.

**Comment by simon-leech** [comment]
Not sure if it would work but perhaps we need to move the 'default' buttons. zoom in / zoom out / zoom to area / admin / logout to the right of the screen in a separate panel. That would remove 5 buttons from the plugin button panel? 
Or we need to just add extra buttons next to the others in the mobile view?

**Comment by dbauszus-glx** [comment]
I think the solution needs to involve some form of scrolling. Splitting the control based on the viewport will be hard and just kick the can down the line for another year when there's too many buttons on either side.

**Comment by dbauszus-glx** [comment]
@simon-leech  Can you create an "admin view on mobile" issue for this?

**Comment by simon-leech** [comment]
@dbauszus-glx deleted the previous comment and moved to this issue for clarity 

https://github.com/GEOLYTIX/xyz/issues/1337

**Comment by simon-leech** [comment]
Also noticed the tab view isn't accessible on mobile. This isn't great as you can click infoj checkboxes that should do something and they do nothing, but it isn't clear to the user. 

We need to allow tabview on mobile to resolve

**Comment by cityremade** [comment]
<img width="591" alt="Screenshot 2024-07-02 at 14 20 53" src="https://github.com/GEOLYTIX/xyz/assets/7070711/864892e9-aa90-414f-b859-8fc17a2115a9">

**Comment by simon-leech** [comment]
On Safari on iPhone, MAPP is unusable. Something is triggering constant refreshes that renders the page unusable. It doesn't seem to happen on Google Chrome on iPhone
