### ISSUE TITLE
Boolean fields

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#128]
I made a slight change to the boolean checkbox.

The checkbox is now also shown when not editable.

In that case the box is disabled and displayed in gray rather than CTA green.

![image](https://user-images.githubusercontent.com/22201617/56580095-b28e1a80-65c9-11e9-9382-f3d6620ba84a.png)

I moved the boolean module from /edit to the main /view for locations.

The method will return with the input disabled if not editable otherwise the onchange event will be attached to the checkbox.

```
  // Create new row and append to table.
  entry.row = _xyz.utils.createElement({
    tag: 'tr',
    appendTo: entry.location.view.node
  });
  
  // Create val table cell with colSpan 2 in the new row to span full width.
  entry.val = _xyz.utils.createElement({
    tag: 'td',
    options: {
      className: 'val',
      colSpan: '2'
    },
    appendTo: entry.row
  });

  const boolean_checkbox = _xyz.utils.createCheckbox({
    label: entry.name || entry.field,
    appendTo: entry.val,
    checked: !!entry.value
  });

  if (!entry.edit) return boolean_checkbox.disabled = true;

  boolean_checkbox.onchange = e => entry.location.view.valChange({
    input: e.target,
    entry: entry,
    value: e.target.checked
  });
```

**Comment by RobAndrewHurst** [comment]
Added to documentation
