### ISSUE TITLE
Review infoj_skip use

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1303]
The way how infoj_skip is used especially for filter feels awkward.

**Comment by simon-leech** [comment]
Infoj skip is a widely used feature when we apply 'templates' layers (shared configurations) and wish to hide certain elements from the users view.

In my opinion the current configuration works well and is quite easy to maintain and set up. 

Is there something you want to alter about the current implementation and a reason for it @dbauszus-glx ?

**Comment by dbauszus-glx** [comment]
The processing is really awkward and inefficient. 

I created a PR which does the same but is much easier to read with only one flag being set on the layer decorator and not iterations in iterations, in iterations for filter as well as location view methods.

```js
  layer.filter.list = layer.infoj
    .filter(entry => entry.filter !== undefined)
    .filter(entry => entry.field !== undefined)
    .filter(entry => !layer.filter?.exclude?.includes(entry.field))
    .filter(entry => ![entry.key, entry.field, entry.query, entry.type, entry.group].some(val => new Set(layer.infoj_skip || []).has(val)))
```

**Comment by dbauszus-glx** [comment]
The layer decorator method still wants a proper documentation once cleaned up... The draw callback which is created with functions inside the decorator is awkward to read, test, and document.

I'd also like to have a look at the filter excludes / includes check doesn't read great.
