### ISSUE TITLE
Cluster panel

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#131]
The cluster panel will no longer be drawn by default.

Until a smarter logic for layer panels in general is found setting the layer property cluster_panel to true will draw the cluster panel.

**Comment by RobAndrewHurst** [comment]
Added into the new documentation

**Comment by cityremade** [comment]
Looks like the module for cluster panel creation is gone..

**Comment by dbauszus-glx** [comment]
It's now available as a script module.

For now I have added this as cluster.js to the queries folder. I will have a think about the folder structure at another day when it is less hot.

This can be added like so in the layer config. /mapp is the dir path for this instance. The script location can also be exchanged with a cdn url.

```
"scripts": {
  "cluster": "/mapp/queries/cluster.js"
}
```

For now it is only dbscan and kmeans. I will think about other params later.

@cityremade  You want to try and add inputs for the style to this script module?
