### ISSUE TITLE
Lines with fills

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#132]
Line geometries which are drawn with fills look buggy.

![image](https://user-images.githubusercontent.com/22201617/56759776-a8b71380-6791-11e9-813f-507bdead18b3.png)

**Comment by cityremade** [comment]
this is linked [#133](https://github.com/GEOLYTIX/xyz/issues/133)

**Comment by cityremade** [comment]
Leave fillOpacity undefined for line styling.
![Screenshot 2019-05-30 at 11 58 33](https://user-images.githubusercontent.com/7070711/58628677-45f5f200-82d2-11e9-9d5c-8dd86b696342.png)

**Comment by cityremade** [comment]
Fixed along with legend symbols.
