### ISSUE TITLE
Type Numeric not displaying

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1328]
**Issue Template**

## Description

An `infoj` entry of `type: numeric` is not displayed. 
Removing type numeric displays information. 
The type numeric should default to 2dp and toLocaleString formatting.

``` json 
{
    "infoj": [
        {
            "field": "a",
            "type":"numeric"
        }
   ]
}
```

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug

**Comment by dbauszus-glx** [comment]
How was this completed?
