### ISSUE TITLE
Lines in styles theme legend

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#133]
Without a fill being specified the symbol in the legend should be a line of the same thickness as the line in the map instead of a square.

![image](https://user-images.githubusercontent.com/22201617/56760079-5296a000-6792-11e9-880f-0456b30a3a2e.png)

**Comment by cityremade** [comment]
This one is a bit tricky as we need to set fill: true on all mvt layers. Without they're flashing while on hover. Any other way we can tell whether a style is a line?

**Comment by dbauszus-glx** [comment]
If fillOpacity is not null?

**Comment by cityremade** [comment]
Done. dev.
![Screenshot 2019-05-30 at 11 57 03](https://user-images.githubusercontent.com/7070711/58628614-13e49000-82d2-11e9-8897-285f0c36f781.png)

**Comment by cityremade** [comment]
![Screenshot 2020-07-14 at 13 42 17](https://user-images.githubusercontent.com/7070711/87426915-e2af4800-c5d7-11ea-9c8f-6a53e27b6278.png)
Lines in legend work - just leave fillOpacity and fillColor unset.

**Comment by cityremade** [comment]
`"Test graduated theme": {
                "field": "detailtype_num",
                "type": "graduated",
                "cat_arr": [
                  {
                    "value": 0,
                    "label": "1",
                    "style": {
                      "strokeWidth": 5,
                      "strokeColor": "#1e88e5" 
                    }
                  },
                  {
                    "value": 1,
                    "label": "2",
                    "style": {
                      "strokeColor": "#66bb6a" 
                    }
                  },
                  {
                    "value": 2,
                    "label": "3",
                    "style": {
                      "strokeColor": "#ef5350" 
                    }
                  }
                ]
              }`
