### ISSUE TITLE
Selection of overlapping polygons

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#135]
There is currently no way to select a polygon which is completely covered by another polygon. A check for all features at locations and a multiple features to select dialog (similar to cluster select) needs to be introduced.

**Comment by dbauszus-glx** [comment]
This should be resolved with the drilldown function in the highlight/select module.

A mouseDown event takes a timestamp.

The singleClick select event checks whether the time passed exceeds a threshold of 600. If this is the case then all the selectable items will be selected.

**Comment by simon-leech** [comment]
Please could we amend the pop-up for the long click to use the Layer Name instead of Layer Key (where one is provided). 
Could we also remove the exclamation mark and instead put the ID of the location into square brackets. 

Layer [6]
Layer [8]
Layer2 [10] 

For example

**Comment by dbauszus-glx** [comment]
Changed in this PR. https://github.com/GEOLYTIX/xyz/pull/568
