### ISSUE TITLE
JSDoc Template and Type Definitions

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1350]
We either need a template in which we can control the nesting of object params or look into creating type definition for known objects such as Mapp-Layer, Mapp-Location, httpRequest, httpResponse, etc.

**Comment by RobAndrewHurst** [comment]
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/b718f813-4464-4bd1-ac79-c8a5b1522212)

It would be great in the future for global typedefs to possibly show a list of place where it is referenced
