### ISSUE TITLE
Inline CSS for mapp.ui elements

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1357]
It should be possible to pre/append CSS rules in a workspace or process environment.

This would be useful instead of creating divs as values within inline styles attached.

It is possible to provide inline css for [infoj-entry] titles, values, and group elements.

Should it be possible to provide inline css to layer view elements like view, group, or panel header?

**Comment by dbauszus-glx** [comment]
This could be solved with a custom template overwriting the default.

The custom templates defined in `process.env.CUSTOM_TEMPLATES` could load a shared CSS document.

**Comment by dbauszus-glx** [comment]
This can also be solved by a plugin which is able to prepend CSS to the document.head on import.
