### ISSUE TITLE
Distribution Jenks

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1372]
**Issue Template**

## Description

A `distribution: jenks` thematic on a mvt layer is correctly updating the legend as you zoom in and out - but all the polygons are rendered the same colour on the map. 
![image](https://github.com/user-attachments/assets/f57024fe-eeff-4faf-a741-f254647c3603)
Example Configuration 
``` json 
{
  "name": "TEST",
  "format": "mvt",
  "tables": {
    "11": null,
    "12": "schema.table"
  },
  "geoms": {
    "12": "geom_3857_25m",
    "13": "geom_3857_25m",
    "14": "geom_3857_5m"
  },
  "wkt_properties": true,
  "srid": "3857",
  "qID": "id",
  "style": { 
   "themes": {
  "Population": {
        "title": "Population",
        "type": "graduated",
        "distribution": "jenks",
        "graduated_breaks": "greater_than",
        "field": "population_current",
        "cat_arr": [
          {
            "style": {
              "fillColor": "#edf8fb"
            }
          },
          {
            "style": {
              "fillColor": "#b2e2e2"
            }
          },
          {
            "style": {
              "fillColor": "#66c2a4"
            }
          },
          {
            "style": {
              "fillColor": "#2ca25f"
            }
          },
          {
            "style": {
              "fillColor": "#006d2c"
            }
          }
        ]
      }
}
}
}
```

## Technical Information
Please delete options that are not relevant.

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug

**Comment by dbauszus-glx** [comment]
The graduated_breaks check must be `less_than`. If breaks are calculated by looking at the distribution of values then all values will be bigger than the smallest.
