### ISSUE TITLE
User defined drive times for catchments

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#139]

**Comment by cityremade** [comment]
Now on dev. Awaiting documentation update.

![Screenshot 2019-05-22 at 11 09 21](https://user-images.githubusercontent.com/7070711/58166775-74485180-7c82-11e9-912e-cc488d74d4dc.png)

**Comment by cityremade** [comment]
@lisataylor-geolytix see dev.

**Comment by cityremade** [comment]
Chapter for documentation @RobAndrewHurst 
[isolines.txt](https://github.com/GEOLYTIX/xyz/files/3231891/isolines.txt)

**Comment by cityremade** [comment]
added to docs.
