### ISSUE TITLE
Workspace Hot Loading 🔥 

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#1390]
It would be really useful for local testing if we could programmatically hot swop workspaces on a already running instance. This can go for swopping out clients and also different workspaces to be used along side browser unit tests.

**Comment by dbauszus-glx** [comment]
This could work by controlling the cache. On a localhost instance we could enable a command to clear the cached workspace. However, I am not seeing in how this is different from reloading the instance which obviously clears the cache.

We could also enable that resources from the file system are never cached and will always be accessed directly from source on execution.

**Comment by RobAndrewHurst** [comment]
We need to revisit this along side the changes on #1440

**Comment by dbauszus-glx** [comment]
I will update the wiki in this regard with the WORKSPACE_AGE now explained in the JSDOC. https://github.com/GEOLYTIX/xyz/issues/1609

**Comment by dbauszus-glx** [comment]
I added information in regards to the WORKSPACE_AGE to the XYZ wiki page. https://github.com/GEOLYTIX/xyz/wiki/XYZ#workspace-api
