### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1397]
We need to look into custom error messages.

The catch for the load plugins for example prints out that something is wrong but not what is wrong. This might look cleaner in the dev console but hides crucial information.

```js
.catch(err => {
  console.error(`Failed to load plugin: ${plugin}`);
  reject(err)
})
```

In this case a plugin failed to load because of the plugin script execution. But without logging the actual error this was impossible to find. We don't want to log each error twice which would just create more mess.

![image](https://github.com/user-attachments/assets/054a6a11-3a4d-476e-94fa-ff0a6eb6b80c)

If the log of the original error which is crucial for finding issues is not enough then we need to find a way of adding custom messages to the error object before logging.

**Comment by simon-leech** [comment]
Could we just do something like this, where we print Failed to load and then the plugin name and then the actual error message? 

``` js 
.catch(err => {
  console.error(`Failed to load plugin: ${plugin}. ${err}`);
}

```

**Comment by dbauszus-glx** [comment]
That's somewhat better but still will be quite hard to find the actual bug. 

You can jump to the line of the exception.

![image](https://github.com/user-attachments/assets/890a186a-39f8-4e1e-9606-e5d6c47d46ff)
