### ISSUE TITLE
Custom class in location view

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#140]
In order to style location view entries in a report or custom view (reports are pretty much custom views) we introduced the class key for infoj entries.

`"class": "_report"` will add the _report css class to the entry in the location view. This may then be used to hide the class in a report.

e.g.

```
        ._report {
            display: none;
        }
```

**Comment by cityremade** [comment]
Tested, works, added to infoj docs.

**Comment by dbauszus-glx** [comment]
In v4 the class value will be assigned to the entry.node element.
