### ISSUE TITLE
workspace.templates lookup in layer query templates

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1410]
Some default query templates use the _.workspace param to replace fields in the template string.

The use of the workspace as a parameter should be prevented and fields must be checked for whitelisted characters.

**Comment by dbauszus-glx** [comment]
#1409 must be consolidated before we can look at this issue.

**Comment by dbauszus-glx** [comment]
Templates can be restricted to roles, but there restrictions do not apply inside the execution of the [query] template render method.

![image](https://github.com/user-attachments/assets/f2e76602-a4ec-4b31-933a-0fc8bd979493)

**Comment by dbauszus-glx** [comment]
Fields should be provided as an array to the template render method. https://github.com/GEOLYTIX/xyz/pull/1595

![image](https://github.com/user-attachments/assets/02776a1c-9d2f-4f72-9f6e-b6cedc19d442)

It should also be possible to add the label param property to the fields array.

![image](https://github.com/user-attachments/assets/d3d1aacf-ef18-4739-95bc-847604cfcbd0)

The lookup for the template can then happen in the layerQuery method of the query module.

**Comment by RobAndrewHurst** [comment]
The json_build_object syntax is wrong in the geojson query template. 

I am reopening for this issue.
