### ISSUE TITLE
ID Look ups for location table views

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#142]
Add the ability to create a location table view, that performs an ID look up specific to the location.

**Comment by dbauszus-glx** [comment]
Isn't that the case anyways?

**Comment by RobAndrewHurst** [comment]
Aren't they Spatial in design ?

**Comment by dbauszus-glx** [comment]
From [report.js](https://github.com/GEOLYTIX/xyz_resources/blob/master/shneame/report.js) in shneame deployment.

```
  _xyz.tableview.locationTable({
    title: 'Age Profile',
    location: {
      layer: params.layer,
      id: params.id
    },
    target: document.getElementById('age_profile')
  });
```

**Comment by cityremade** [comment]
![Screenshot 2019-07-17 at 07 40 50](https://user-images.githubusercontent.com/7070711/61349969-463c5380-a866-11e9-8a4f-87288f766758.png)
Done and added to docs.
