### ISSUE TITLE
workspace api /test src string sources

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1430]
A method should be made available to administrators to test all sources in a workspace.

This can be done by iterating through every workspace template getting the template from source and logging the error in an array.

If the template contains a src the nested sources will be tested as well, adding the errors to the error array to be returned from the /test endpoint.

**Comment by RobAndrewHurst** [comment]
We need to determine the pass/fail criteria.

**Comment by dbauszus-glx** [comment]
> We need to determine the pass/fail criteria.

Any src which fails in a getFrom(src)

**Comment by dbauszus-glx** [comment]
It is important that the envReplace method is run in the test. Hence we can only look at this after #1409 has been merged.
