### ISSUE TITLE
Cookie Consent & Storage 🗳 🍪 

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#1498]
Ideally we would have users separately agree to send product analytics once we want to place these on live apps.

* should the consent be requested on registration (register view) or first login (in-app)
* flag for consent should be stored in the user object - introduce a new field in acl
* eventually user to be able to withdraw consent (within prospective user settings area)

**Comment by dbauszus-glx** [comment]
Not in registration since the terms may change. If you add consent to registration than you cannot record users already registered.

Not on login since we use custom logins and you don't want to add or remove bits on different logins for different instances with different plugin.

Option A: Confirm dialog when a plugin which records user sessions is initialised.

Option B: an array of notifications, including the use of cookies to be displayed in a [ui toast](https://github.com/GEOLYTIX/xyz/issues/1489). 🍞

**Comment by cityremade** [comment]
yes, definitely should be only offered when tracking is about to initialize.

**Comment by cityremade** [comment]
User consent should be required as early as the login screen.
They need to be aware of the use of secure app cookies, third party cookies (like optional API services) and eventually possible product analytics. 

Here's a possible general workflow:
<img width="680" alt="Screenshot 2024-10-03 at 12 11 03" src="https://github.com/user-attachments/assets/dec8390e-3319-4a56-aa9b-d9f07479d992">

I like the idea of storing user consent object in Local Storage in order to prevent unlogged users from being asked again and again. If consent object is not found locally it should be requested again. Otherwise consent is applied accordingly. 

We need to keep log of these settings on our side so the consent when first given/altered should be sent to user update endpoint. 

Lastly, the users need to be given a possibility to change their preferences within the user area which we have in scope. 

Here's a codepen with a concept of storing user consent using Locale Storage:
https://codepen.io/sebastian-marinescu/pen/MWwGLwY

**Comment by dbauszus-glx** [comment]
Before we get swamped into complex details can we clarify first the use of the user cookie.

The login process returns a cookie on redirect.

GDPR requires consent before deploying a cookie.

I can see two options here. Updating the text to explain that a user cookie will be deployed to grant access to the xyz host.

Or a checkbox which must be ticked explicitly stating that the user agrees to the use of a cookie required to login.

**Comment by dbauszus-glx** [comment]
The mapp library uses a cookie for access only. Any third party library which requires cookies can be loaded in plugins. A plugin which requires a cookie should ask for consent or not load.

There is an issue in regards to the redirect cookie which I will address. https://github.com/GEOLYTIX/xyz/issues/1532

**Comment by cityremade** [comment]
> Before we get swamped into complex details can we clarify first the use of the user cookie.
> 
> The login process returns a cookie on redirect.
> 
> GDPR requires consent before deploying a cookie.
> 
> I can see two options here. Updating the text to explain that a user cookie will be deployed to grant access to the xyz host.
> 
> Or a checkbox which must be ticked explicitly stating that the user agrees to the use of a cookie required to login.

I would say this is `strictly necessary` cookie which we have to notify about still as a condition to use the service.

**Comment by cityremade** [comment]
<img width="877" alt="Screenshot 2024-10-03 at 14 37 47" src="https://github.com/user-attachments/assets/ffabe682-b7fb-43a8-a0e4-891b58862b09">
example from DW https://www.dw.com/en/

**Comment by dbauszus-glx** [comment]
How is that supposed to work on the login screen?

Clicking the login button dispatches a cookie. Consent must be given either before or with the click of the login button.

**Comment by cityremade** [comment]
It should pop up immediately on login screen. Once we got the consent (full or limited) we let them go on to login.

**Comment by dbauszus-glx** [comment]
This is currently solved with a plugin. https://github.com/GEOLYTIX/mapp/blob/main/plugins/cookie_consent.js
