### ISSUE TITLE
Comma Decimal in Numeric Formatter for Slider Element

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1499]
The numeric formatter fails on slider element input elements for a user with a locale that uses comma decimals, eg. DE 🇩🇪

The comma seperator isn't displayed and the return is an integer instead of a float.

![image](https://github.com/user-attachments/assets/83d3ec1f-d441-476a-bae7-02b0d7b2761c)

**Comment by dbauszus-glx** [comment]
I believe the issue to be unformatStringValue method of the numericFormatter module

![image](https://github.com/user-attachments/assets/f2b823f9-69e7-4620-8f7f-5a7b0864b3f8)

![image](https://github.com/user-attachments/assets/55db4ff4-3def-4b68-ab03-e729fa14688d)

**Comment by RobAndrewHurst** [comment]
https://github.com/GEOLYTIX/xyz/pull/1503

This is currently awaiting testing and approval.
