### ISSUE TITLE
Thematic styling of location geometries.

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#151]
The value for a location's geometry entry maybe a feature collection returned as geojson from a complex lookup defined as a fieldfx.

It should be possible to assign a theme with the same format as provided in layer styles to the feature collection. The theme should be in the style definition which is already part of the geometry entry definition.

**Comment by geolytix-xyz** [comment]
Originally requested by M&S

They had catchments that were made up of OAs and instead of having the catchment as all one colour they wanted to be able to apply different colours based on metrics e.g. % of sales, population

**Comment by dbauszus-glx** [comment]
Currently location geometries have a fixed styling retrieved from the geometry field entry.

It should be possible to assign a thematic style.

**Comment by dbauszus-glx** [comment]
Currently the thematic styles are part of the individual layer style methods. It is required to uncouple the different thematic style functions first which well then allow these function to return a style to method which renders location geometries.

**Comment by cityremade** [comment]
possible setup to return feature collection with feature properties:
`,
                        {
                            "name": "All catchments",
                            "type": "geometry",
                            "field": "all_catchments",
                            "fieldfx": "SELECT jsonb_build_object('type', 'FeatureCollection','features', b.features) AS collection FROM (SELECT jsonb_build_array(jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'primary', 'id', id),'geometry', ST_AsGeoJson(catchment_primary)::jsonb),jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'secondary', 'id', id),'geometry', ST_AsGeoJson(catchment_secondary)::jsonb),jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'tertiary', 'id', id),'geometry', ST_AsGeoJson(catchment_tertiary)::jsonb)) AS features FROM (SELECT * FROM dev.storelist_1507__19 where id = $1) a) b"
                        }`

Working further on themes for feature collections.

**Comment by cityremade** [comment]
![Screenshot 2020-01-28 at 11 52 37](https://user-images.githubusercontent.com/7070711/73261786-b25c2480-41c4-11ea-94cc-430f9b65bf49.png)
I need to put a legend for these somewhere. Or would it it better to have labels.

**Comment by dbauszus-glx** [comment]
Yes, legend as flag please.

{ legend: true }

With the legend to be added to the infoj dom container. Not unlike the control for isolines for example.

**Comment by cityremade** [comment]
Added legend
![Screenshot 2020-03-10 at 17 42 59](https://user-images.githubusercontent.com/7070711/76342509-a05abf00-62f6-11ea-994b-2d4311a6a60f.png)

**Comment by cityremade** [comment]
ok. here's updated example:

`{
                            "name": "All catchments",
                            "type": "geometry",
                            "class": "_report",
                            "display": true,
                            "style": {
                                "theme": {
                                    "legend": true,
                                    "type": "categorized",
                                    "field": "catchment",
                                    "cat": {
                                        "primary": {
                                            "label": "Primary",
                                            "style": {
                                                "strokeColor": "#5E08E4",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#5E08E4"
                                            }
                                        },
                                        "secondary": {
                                            "label": "Secondary",
                                            "style": {
                                                "strokeColor": "#D15CF1",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#D15CF1"
                                            }
                                        },
                                        "tertiary": {
                                            "label": "Tertiary",
                                            "style": {
                                                "strokeColor": "#FFB9F2",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#FFB9F2"
                                            }
                                        }
                                    }
                                }
                            },
                            "field": "all_catchments",
                            "fieldfx": "SELECT jsonb_build_object('type', 'FeatureCollection','features', b.features) AS collection FROM (SELECT jsonb_build_array(jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'primary', 'id', id),'geometry', ST_AsGeoJson(catchment_primary)::jsonb),jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'secondary', 'id', id),'geometry', ST_AsGeoJson(catchment_secondary)::jsonb),jsonb_build_object('type', 'Feature','properties', jsonb_build_object('catchment', 'tertiary', 'id', id),'geometry', ST_AsGeoJson(catchment_tertiary)::jsonb)) AS features FROM (SELECT * FROM dev.storelist_1507__19 where id = $1) a) b"
                        }`

**Comment by cityremade** [comment]
Another example with different dataset:

`{
                        	"name": "Styled Catchments",
                        	"field": "drivetimes",
                        	"fieldfx": "SELECT jsonb_build_object('type', 'FeatureCollection', 'features', a.features) FROM (SELECT jsonb_agg(jsonb_build_object('type', 'Feature', 'properties', jsonb_build_object('catchment_band', catchment_band, 'id', storeid), 'geometry', ST_AsGeoJSON(geom_4326)::jsonb)) as features FROM <this table> WHERE storeid = $1) a",
                        	"type": "geometry",
                        	"display": true,
                            "style": {
                                "theme": {
                                   
![Screenshot 2020-03-24 at 14 09 55](https://user-images.githubusercontent.com/7070711/77434690-25ef6c00-6dd9-11ea-946a-ec74ada23b83.png)
"legend": true,
                                    "type": "categorized",
                                    "field": "catchment_band",
                                    "cat": {
                                        "Top 20%": {
                                            "label": "Top 20%",
                                            "style": {
                                                "strokeColor": "#005824",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#005824"
                                            }
                                        },
                                        "20-40%": {
                                            "label": "20-40%",
                                            "style": {
                                                "strokeColor": "#41AE76",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#41AE76"
                                            }
                                        },
                                        "40-60%": {
                                            "label": "40-60%",
                                            "style": {
                                                "strokeColor": "#99D8C9",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#99D8C9"
                                            }
                                        },
                                        "60-80%": {
                                            "label": "60-80%",
                                            "style": {
                                                "strokeColor": "#D8F793",
                                                "fillOpacity": 0.7,
                                                "fillColor": "#D8F793"
                                            }
                                        }
                                    }
                                }
                            }
                        }`

**Comment by cityremade** [comment]
Done ages go.
