### ISSUE TITLE
showDialog method

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1513]
It shouldn't be required to recreate a dialog wanting to show a dialog already created. There should be a showDialog method allowing us to simply show the dialog again which retains all it's content elements.

**Comment by RobAndrewHurst** [comment]
Provided a show method for dialogs. This will prevent the recreation of dialogs that already exist.
Specifying new: true within the dialog params will prevent the show method form being provided.

added logic to check if there is a node and dialog.show is a function then it will be called. There isn't a need to check on new as the only way to get dialog.show is if new is specified.
