### ISSUE TITLE
_redirect cookie use

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1532]
The mod/user/login script deploys a redirect cookie to redirect a user from the login view to the previous view. This cookie is only required for the login process.

The default view request a user cookie no matter whether the login is public or private.

The cookie request is routed through the routes User API, which will go through the login view for an undefined user and dispatch the redirect cookie which is never used.

**Comment by dbauszus-glx** [comment]
#1535 addresses some if these issues. The redirect cookie will be destroyed on successful login when the redirect location is set on the header.

However the redirect cookie will hang around forever on log out and when the login doesn't conclude. A cookie should not be used for redirection. #1535 adds a test where the redirect param is passed to the login view for inclusion in the request body for user authentication.

**Comment by RobAndrewHurst** [comment]
The redirect cookie is created to redirect (set the response header location) in the login module.

The cookie method which is called to renew a cookie must not attempt to create a new cookie and return the login view which will cause the creation of a redirect cookie on public instances. Instead the cookie should return false without parameters and only attempt to create a new cookie with the create url parameter flag.

Some param, property, and typedef confusion has been resolved in the function docs.

This PR adds the redirect value to the request params to be substituted in the english default login view. This is a test to get eventually rid of the redirect cookie.
