### ISSUE TITLE
Style Legend Classification Toggling Should Not Apply a Filter 

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1543]
**Issue Template**

## Description

When using a `categorized` theme, you have the option to click on a category to toggle its display. However, what this actually does is run a query to the database adding to the `layer.filter.current`. 

There is 2 main issues with this: 
1. A field template lookup for the thematic will always crash as that field will never exist , in the example below `field_1` is a calculated field not an actual field on the database.
``` json
  "theme": {
        "title": "Theme",
        "type": "categorized",
        "field": "field_1",
        "template": {
          "key": "field_1",
          "template": "CASE WHEN field_2 > 60 THEN 'Pedestrian' WHEN field_3 > 75 THEN 'Vehicular' ELSE 'Mixed' END"
        },
        "cat": {
          "Pedestrian": {
            "label": "Mainly Pedestrian",
            "fillColor": "#9A87ED"
          },
          "Vehicle": {
            "label": "Mainly Vehicle",
            "fillColor": "#002698"
          },
          "Mixed": {
            "fillColor": "#CDCDCD"
          }
        }
      }

```

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug
- ✅ New Feature

## Proposed Solution

I propose that instead of adding / removing from the `layer.filter.current` , instead the toggle in the style legend is simply visual. 
It will just set the styling for locations that meet that criteria to null. This will reduce calls to the db, be cleaner as the filters are only applied from the filter panel, and would mean that calculated fields are supported

**Comment by RobAndrewHurst** [comment]
It should be possible to toggle categories in a legend without applying a filter.

This was already possible through the featureFilter but untested, awkward, and undocumented.

The featureFilter method has now been removed.

The categorized theme method will set the feature style to null if the cat.style is null.

The featureStyle method will shortcircuit after the theme method if the feature.style is null.

The `theme.filterOnly` indicates that a theme [style only] filter should be applied.

The onclick method for the cat element label in the categorized legend cat iteration has been unnested into its own method catToggle.

The catToggle method sets the cat style to null if toggled and restores the style from the cat._style property if toggled off.

The filterAdd and filterRemove methods will add or remove the cat value to the cat field filter. These methods will shortcircuit if the theme.filter is not set.

The theme.filter will be set from style.filter for all themes in a layer.style.
