### ISSUE TITLE
Selected Filter Options in a Dropdown need a selected Class Applied

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1546]
**Issue Template**

## Description

I have two filters applied to the layer.
![image](https://github.com/user-attachments/assets/5f38ccb7-2f98-42b5-8599-ddf6875f85bb)
 
The Filter Dropdown doesn't have a selected class applied to the selected filters, so I don't know what is already selected.
![image](https://github.com/user-attachments/assets/d9b3e8d5-bc80-450e-ab7a-46a1663a206a)

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug
- ✅ CSS

**Comment by dbauszus-glx** [comment]
This can be implemented by adding the asscoiated li element to the filter object allowing to toggle the status when the filter is applied or removed.

Should selecting an existing filter remove the filter or just shortcircuit?
