### ISSUE TITLE
Horizontal scrollbar in table view

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#155]
The horizontal scrollbar in the tableview should always be visible. Not only when the table is scrolled all the way to the bottom.

![image](https://user-images.githubusercontent.com/22201617/62290916-610fea00-b45a-11e9-95df-072d1c5ea85b.png)

**Comment by cityremade** [comment]
Now table is no longer a standalone element, it can sit in an html template with custom styling.

**Comment by dbauszus-glx** [comment]
fixed_header must be set to true in the dataview object in order to enable a fixed header.
