### ISSUE TITLE
Infoj Entry - Layer Dependents 

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1578]
## Description

It needs to be possible to reload other layers when an infoj entry is altered.

Use Case
1. Layer A contains Sites that have a catchment that is a 500m buffer when the Site is set to 'Big' or 250m buffer when the Site is set to 'Small'. This is handled by a db trigger function.
2. Layer B is an mvt layer that simply shows the Sites Catchments.
3. We need to be able to specify that layer B should be reloaded, when a Site on Layer A is changed.

Will add a new array called layer_dependents that are simply reloaded when the entry is edited.

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 
- ✅ New Feature

**Comment by RobAndrewHurst** [comment]
https://github.com/GEOLYTIX/xyz/pull/1577/commits/42c8059294e0b86ce040e1c24a38f1c846daf84c

The map method which returns a flat array of all the dependents string can check for each string in the dependents_layer array and reload the layer if matched in the associated mapview.

```js
  // Find newValue entries for update.
  const dependents = this.infoj
    .filter(entry => typeof entry.newValue !== 'undefined')
    .map(entry => {

      // Update entry.values with newValues.
      entry.value = entry.newValue;

      if (Array.isArray(entry.dependents_layer)) {

        entry.dependents_layer.forEach(layer => {

          // Iterate through the dependents_layer array and reload matching layers in mapview.
          entry.location.layer.mapview.layers[layer].reload()
        })
      }

      return entry.dependents
    }).flat()
```
