### ISSUE TITLE
Tooltips for layer view drawer

### ISSUE THREAD

**Issue by jfitzpatrick17** [GEOLYTIX/xyz#1594]
## Description

It isn't obvious to some users that layers can be expanded (to reveal layer descriptions, style settings/legends and filters). Being able to add tooltips to a layer would enable users to access information about a layer, before having to expand. It would also help to reduce the space taken up in the left-hand panel (from layer descriptions in the meta).

On a mobile, layer tooltips could be disabled.

## Type of Issue 

- ✅ New Feature

**Comment by dbauszus-glx** [comment]
We can add tooltips but we cannot replace the meta tag.

- This would break legacy support.
- The meta tag can include html, a tooltip cannot.
- Tooltips are not avilable on touch screen.

At best this will add complexity but won't get rid of the meta tag.

**Comment by cityremade** [comment]
<img width="210" alt="Screenshot 2024-10-28 at 10 01 17" src="https://github.com/user-attachments/assets/32acfe5f-0e08-4dfa-a285-6388a4260046">

optional information modal?

**Comment by dbauszus-glx** [comment]
adding a button to the header for the information to show in a dialog would be my preferred option.

**Comment by RobAndrewHurst** [comment]
Needs further specification!
