### ISSUE TITLE
Layer display toggle button has no layer identifier.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#1629]
At the moment for analytics needs we cannot tell which layer is the parent of each display toggle without an acrobatic selector.

To add a data attribute to hold layer key apart from only data-id=display-toggle for each element.

It would make it clear which layer was toggled.

I don't mind adding it to .header. Way better than 3rd parent.

**Comment by dbauszus-glx** [comment]
Yeah. The assignment of `layer-drawer` as data-id is bad. Let me fix this.
