### ISSUE TITLE
Tabview Open More by Default

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1631]
## Description

It has been mentioned a lot by clients that it's unclear what the purpose of the tabview is, as it only opens so you can see the header by default. So it is isn't obvious what it does / what it contains.
The tabview should open by default more than it currently does so you can see the data within it. 

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ New Feature

**Comment by RobAndrewHurst** [comment]
@simon-leech @dbauszus-glx Do you think it would be worth while to also add a double click event on the tabview that could trigger it to expand and collapse?

**Comment by jfitzpatrick17** [comment]
I like that idea, when I showed it to a user who hadn't used mapp before, they first tried to click on the tab to see if it would open (like you would do on a desktop taskbar)

**Comment by dbauszus-glx** [comment]
Not for me the double click event. Not easy to implement and doesn't solve the issue referenced in this ticket. How would a use know that there is a double click event on a element where he doesn't know there is a single click event. Can you create a ticket for the mapp.ui.utils.resizeHandler if you want to support a double click on these type of elements. The tabview tab bar itself should not mush in more click events that potentially interfere with the selection.

**Comment by RobAndrewHurst** [comment]
> Not for me the double click event. Not easy to implement and doesn't solve the issue referenced in this ticket. How would a user know that there is a double click event on a element where they doesn't know that there is a single click event move event. Can you create a ticket for the mapp.ui.utils.resizeHandler if you want to support a double click on these type of elements. The tabview tab bar itself should not mush in more click events that potentially interfere with the selection of tabs.

No worries just a thought! :)
