### ISSUE TITLE
Cloudfront Provider; use of node-fetch

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#1641]
## Description

There is old legacy code in the cloudfront provider that is using the (node-fetch) package that was phased out over 2 years a go.
We noticed it would break after removing bcrypt as a dependency for the application.

--Before--

```js
const nodeFetch = require('node-fetch')
```

```js
const response = await nodeFetch(signedURL)
```

--After--

```js
const response = await fetch(signedURL)
```

We need to remove the require statement from the module & change the fetch reference in the code.

- ✅ Bug

**Comment by dbauszus-glx** [comment]
There are other issues with the cloudfront module as commented in the PR. Should these be addressed in this PR or do you want to create a separate issue for the Error handling?
