### ISSUE TITLE
Spread this.location.layer.queryparams

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1648]
Spread this.location.layer queryparams

this.location.layer.queryparams need to be spread into the dataview. Otherwise if the location layer has queryparams they are not passed to the dataview entry, resulting in failing queries in custom views.

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug

**Comment by dbauszus-glx** [comment]
Issue has been resolved in PR.
