### ISSUE TITLE
Date and datetime format methods are private in date entry.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#1694]
At the moment unix timestamp => date/datetime formatters are private inside date element module.

Conversion from string date to unix is straightforward like this:
`Math.floor(new Date(<string date>).getTime() / 1000)`

Yet going from unix timestamp into string date is more problematic as editable date input only takes specific format.

How to solve:

inside ui/locations/entries/date.mjs `formats` (line 8) moved into utils so that can be reused outside date entry.

**Update**: the plugin in question for apps v480 assigns these methods to mapp.utils so that they can be used in the plugin context.

Still to implement for the framework.

**Comment by dbauszus-glx** [comment]
ui/locations/entries/date.mjs must also be documented. It would be good to move the dateString, timeString, and formats object/method to their own utils module.

```js
const dateString = entry => new Date((entry.newValue || entry.value) * 1000)
  .toLocaleDateString(entry.locale, entry.options); // day only as configured in workspace

const timeString = entry => new Date((entry.newValue || entry.value) * 1000)
  .toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); // time only as 00:00

// formatted value for input element.
const formats = {
  datetime: entry => `${new Date((entry.newValue || entry.value) * 1000).toLocaleDateString('fr-CA')}T${timeString(entry)}`, // YYYY-MM-DDT00:00
  date: entry => `${new Date((entry.newValue || entry.value) * 1000).toLocaleDateString('fr-CA')}` // YYYY-MM-DD
}
```

I suggest a temporal module as there will be a temporal web api in the future.

eg.

```js
mapp.utils.temporal = {
  dateString,
  timeString,
  datetime, // from formats object
  date // from formats object
}
```

**Comment by RobAndrewHurst** [comment]
> ui/locations/entries/date.mjs must also be documented. It would be good to move the dateString, timeString, and formats object/method to their own utils module.
> 
> ```js
> const dateString = entry => new Date((entry.newValue || entry.value) * 1000)
>   .toLocaleDateString(entry.locale, entry.options); // day only as configured in workspace
> 
> const timeString = entry => new Date((entry.newValue || entry.value) * 1000)
>   .toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); // time only as 00:00
> 
> // formatted value for input element.
> const formats = {
>   datetime: entry => `${new Date((entry.newValue || entry.value) * 1000).toLocaleDateString('fr-CA')}T${timeString(entry)}`, // YYYY-MM-DDT00:00
>   date: entry => `${new Date((entry.newValue || entry.value) * 1000).toLocaleDateString('fr-CA')}` // YYYY-MM-DD
> }
> ```
> 
> I suggest a temporal module as there will be a temporal web api in the future.
> 
> eg.
> 
> ```js
> mapp.utils.temporal = {
>   dateString,
>   timeString,
>   datetime, // from formats object
>   date // from formats object
> }
> ```

https://github.com/tc39/proposal-temporal

I think we should hold on this as until its added there is no point in creating further confusion as we will want to re-review this functionality because temporal is different in many different ways :)
