### ISSUE TITLE
Roles stripped from layer nested in a locale.

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#1696]
## Description

Roles on a locale are being removed as they need to not be sent to the client when requested.
They can however remain in the workspace cache in the process.

We need to create a function to remove the roles objects from the locale endpoint so they are not sent to the client on request.

We also need better tests to see when a layer has the correct roles as it can't come from the locale endpoint.

## Type of Issue 
- ✅ Bug
- ✅ Testing

### Extra context

as mentioned from @dbauszus-glx 

> To better understand this is a particular issues for roles on nested objects.
> 
> A layer nested in a locale will have it's roles stripped when the locale is processed before the layer is processed.
> 
> Roles should be stripped in the _workspace module before a JSON object is returned to the client.

**Comment by dbauszus-glx** [comment]
To better understand this is a particular issues for roles on nested objects.

A layer nested in a locale will have it's roles stripped when the locale is processed before the layer is processed.

Roles should be stripped in the _workspace module before a JSON object is returned to the client.

**Comment by dbauszus-glx** [comment]
This must be applied to the layer as well.

I have a layer with a literal role and my user has the role.

```json
"layers": {
      "OSM": {
        "display": true,
        "format": "tiles",
        "URI": "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        "attribution": {
          "© OpenStreetMap": "http://www.openstreetmap.org/copyright"
        },
        "template": "merge_into",
        "_templates": ["merge_from"],
        "roles": {
          "literal": null
        }
      }
```

Requesting the layer through the workspace API the role object should be stripped.

![image](https://github.com/user-attachments/assets/6b6844e6-7024-4f86-a2b3-dd10fde798da)
