### ISSUE TITLE
make cache tables unlogged

### ISSUE THREAD

**Issue by rhysallister** [GEOLYTIX/xyz#171]
Using an unlogged table for the cache could provide a non trivial increase in speed.

**Comment by dbauszus-glx** [comment]
I have added an alter table statement prior to the index creation when a new cache table is created in the checkLayers module.

```
  let rows = await env.dbs[layer.dbs](`
    Create table ${layer.mvt_cache}
    (
      z integer not null,
      x integer not null,
      y integer not null,
      mvt bytea,
      tile geometry(Polygon, ${layer.srid}),
      constraint ${layer.mvt_cache.replace(/\./,'_')}_z_x_y_pk
        primary key (z, x, y)
    );

    Alter table ${layer.mvt_cache} set unlogged;
    
    Create index ${layer.mvt_cache.replace(/\./,'_')}_tile on ${layer.mvt_cache} (tile);`);
```

**Comment by dbauszus-glx** [comment]
I also found this article which explains more the benefits and constraints of unlogged PostgreSQL tables. https://www.compose.com/articles/faster-performance-with-unlogged-tables-in-postgresql/
