### ISSUE TITLE
Layers not cloned when added to multiple map views

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1717]
When using a custom view that creates multiple map views, there is some odd behaviour with layers added to map views. 

Workflow 
- Get the locale 
- Set layers to locale.layers
- Create a map view 
- Add layers to it
- Create second map view 
- Add same layers to this
- Change a theme on the second map view on a layer, the behaviour does not work, it may change the theme or perhaps the theme is reversed multiple times incorrectly too as the layer is decorated over and over. 

Will provide a replicable example next week

**Comment by RobAndrewHurst** [comment]
I am looking into this!
