### ISSUE TITLE
Dataview Toolbar - Visible when entry is display false

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1739]
A Dataview Toolbar is still visible when the entry of type dataview is display false.
The Toolbar should only be visible if the entry is display true.

**Comment by dbauszus-glx** [comment]
I reopen the issue since the bug persist when the toolbar is for dataview in the tabview.

The tabview add/show tab method calls an activate method which must check for and display the toolbar in the tab panel.
