### ISSUE TITLE
Serverless architecture

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#18]
We need to improve the utilization of the hardware which runs the node application. Ideally the node framework itself should be run in a serverless architecture.

A particular challenge will be the use [Puppeteer ](https://developers.google.com/web/tools/puppeteer/) for the server side creation of PDF reports.

The MongoDB security database which holds user accounts will have to be moved to the cloud.

**Comment by jnicho02** [comment]
Which version of Postgres did you say was needed? I believe that since 27 Feb AWS now has 10.1 https://aws.amazon.com/about-aws/whats-new/2018/02/postgresql-10-now-supported-in-amazon-rds/

**Comment by dbauszus-glx** [comment]
It's the version of PostGIS. I need 2.4 for the [ST_AsMVT](http://postgis.net/docs//ST_AsMVT.html) and [ST_AsMVTGeom](http://postgis.net/docs/ST_AsMVTGeom.html) functions.

**Comment by dbauszus-glx** [comment]
MongoDB has been retired and [the repository run steady serverless on Zeit Now](https://medium.com/@goldrydigital/the-zeit-is-now-for-serverless-web-mapping-77edebfaf17e).
