### ISSUE TITLE
Drawing circle doesnt save geometry.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#182]
Circle is saved but geometry is blank.

**Comment by dbauszus-glx** [comment]
Geojson does not support circle geometries.

I break the circle geometry now down into a regular polygon with 33 sides.

This can be adjusted in the circle.mjs module.

![image](https://user-images.githubusercontent.com/22201617/69443757-f3f4cd00-0d46-11ea-8ccd-28d0cf65a119.png)

**Comment by cityremade** [comment]
I used turf for circle geometry before.

**Comment by dbauszus-glx** [comment]
no need. OL has most of the turf stuff built in.

**Comment by dbauszus-glx** [comment]
i already put this in. should be fixed in current development branch.
