### ISSUE TITLE
Mvt's not being removed from Map

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#184]
Mv'ts are not being removed from the map after zooming out past their zoomlevel.

 
![image](https://user-images.githubusercontent.com/43169158/69434385-2e119f00-0d46-11ea-8671-6b6c1f3d341c.png)

**Comment by dbauszus-glx** [comment]
Fixed by adding source.clear to the return from current table check in the mvt tileUrlFunction function.
