### ISSUE TITLE
Legend labels not aligned with icon.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#189]
The label text is not lining up perfectly in a legend with icons, for example SVG.

![image](https://user-images.githubusercontent.com/22201617/69560136-3286c380-0fa3-11ea-9532-4d38790d7a8a.png)

**Comment by cityremade** [comment]
![Screenshot 2019-12-12 at 14 42 45](https://user-images.githubusercontent.com/7070711/70721548-ab995100-1ced-11ea-8e74-7789a687f088.png)

Legend changed to grid with better alignment and spacing. Only symbols are svg as of now.
