### ISSUE TITLE
z-index for location geometry layer

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#193]
Currently the marker is drawn first with additional geometries as layer being drawn on top of the marker.

This isn't great.

![image](https://user-images.githubusercontent.com/22201617/69565338-ada0a780-0fac-11ea-9fe3-57009541e7d0.png)

**Comment by cityremade** [comment]
With today's addition the following changes:

layers 'tiles' drawn on z-index -1,
other layers drawn on z-index 1 unless set otherwise in configuration,

selected location:
- additional geometries at z-index 1998,
- selected location at z-index 1999,
- letter marker at z-index 2000.

**Comment by cityremade** [comment]
Added to geometry docs.
