### ISSUE TITLE
Set null to an array of fields.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#194]
/api/location/edit/field/setnull sets a field of a location to null.

Added to this method was a flag. Whether meta is provided as a field then this field is also set to null.

The method should be changed to accept an array of fields.

e.g. If fields [foo, bar, meta] then these 3 fields will be set to null.

We don't want to introduce exception unless there is no simple way and more general way to achieve the same thing.

**Comment by cityremade** [comment]
Done, can send array to set null.
