### ISSUE TITLE
Partial updates of location info

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#196]
Currently we do only complete updates of the location info. If a geometry is stored in a location field the complete location is reloaded.

We need to think about a method where only updated fields are requested once a location geometry is modified.

**Comment by geolytix-xyz** [comment]
Does this refer to behaviour in v2 only as in M&B v1 when you draw drivetimes the primary catchments don't seem to appear.  Or is that as the primary and secondary catchments don't appear by default?

**Comment by dbauszus-glx** [comment]
This is unrelated. It is easy to add a flag `display: true` to control whether a geometry should be shown. This would however mean that existing workspaces without the flag will not be shown by default.

The issue in this post is what should happen if a new geometry is created. At the moment the complete infoj updates since some values may be related to the geometry. For example a count of points inside a newly created isochrone polygon.

What could happen is that the infoj is parsed upon creation of the polygon and only fields which are affected (regex check on the geometry field name) will be updated accordingly.

**Comment by dbauszus-glx** [comment]
This works now as follows.

After the update the entries with newValues are filtered from the infoj array.

If the entry has a dependents array then we iterate through the dependents.

If a dependent matches a _field_ (unique) of another entry that entry value will be updated.

If a dependent matches a query of another entry and that entry has an update method associated with a dataview then the update method will be called.

```
    location.infoj
      .filter(entry => typeof entry.newValue !== 'undefined')
      .forEach(entry => {

        entry.dependents && entry.dependents.forEach(dependent => {
          if (location.infoj.some(entry => entry.field === dependent)) return dependents.push(dependent);
          location.infoj
            .filter(entry => entry.query === dependent)
            .forEach(entry => entry.update && entry.update());
        });

        entry.value = entry.newValue;
        delete entry.newValue;
      });
```

There after the view will be updated. New values will be shown the updated dataviews will be added to where they belong.
