### ISSUE TITLE
Dashboard templates

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#199]
It would be nice to have the capability to define a html template / snippet for dashboard type entries.

The idea is to have these templates act similar to reports but instead of opening a report in a new page the dashboard could be opened in the dataviews control of the desktop interface.

This would allow to have tables, charts, maps, etc in one dashboard.

```
 {
  "type": "dashboard",
  "title": "Sample Dashboard",
  "display": true,
  "template": "path/to/template.html"
},
```

**Comment by cityremade** [comment]
Templates now introduced to layer dashboards.

**Comment by cityremade** [comment]
Retired - new logic in place.
