### ISSUE TITLE
Hide layer style panel

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#204]
The layer style panel will not be added to the layer view if `hidden: true` in the layer's style object.

```
  "style": {
    "hidden": true,
    "marker": {
        "type": "target",
        "fillColor": "#D8D8F6",
        "layers": {
            "0.6": "#A37871"
        }
    },
    "markerMulti": {
        "type": "target",
        "fillColor": "#D8D8F6",
        "layers": {
            "0.6": "#A37871"
        }
    }
}
```

![image](https://user-images.githubusercontent.com/22201617/69638140-0d9d5980-1052-11ea-8936-627c1dc281b7.png)

**Comment by cityremade** [comment]
I'd rename to it to 'expanded' to keep consistent with locationview groups and charts.

**Comment by dbauszus-glx** [comment]
It's not collapsed, It's not added at all when set to hidden.

**Comment by dbauszus-glx** [comment]
It's still work in progress as themes and styles will become more complex in the future.
