### ISSUE TITLE
The logout button is not clearly visible.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#214]
Change the icon of the logout button from the face-icon to a more identifiable icon.

**Comment by cityremade** [comment]
![Screenshot 2020-01-14 at 14 49 23](https://user-images.githubusercontent.com/7070711/72354114-136ffc80-36dd-11ea-835c-f50640859611.png)
?

**Comment by cityremade** [comment]
![Screenshot 2020-01-14 at 14 57 27](https://user-images.githubusercontent.com/7070711/72354744-3058ff80-36de-11ea-80b9-7e91eab5f96b.png)
This order is better.
