### ISSUE TITLE
Categorized layers don't show a category named "0": 

### ISSUE THREAD

**Issue by fazzer14** [GEOLYTIX/xyz#227]
```
"cat": {
  "0": {
```

When using the above category the styling is not picked up. It resorts to the default colour scheme.
The bug could cause the end-user to draw the wrong conclusions in an area if not picked up when creating.

**Comment by fazzer14** [comment]
"cat": {
	"0": {
		"label": "0",
		"style": {
		"fillColor": "#ffffcc"
		}
when using the above category the styling is not picked up. It resorts to the default colour scheme. 
The bug could cause the end-user to draw the wrong conclusions in an area if not picked up when creating

**Comment by dbauszus-glx** [comment]
I assume this may be caused by 0 being a falsy value. @RobAndrewHurst  can you create some sample data for the dev workspace?

**Comment by cityremade** [comment]
Works for me on dev: 
![Screenshot 2020-01-13 at 10 53 35](https://user-images.githubusercontent.com/7070711/72250242-0ecf1980-35f3-11ea-9f33-8500a4d81241.png)

**Comment by cityremade** [comment]
![Screenshot 2020-01-13 at 11 56 40](https://user-images.githubusercontent.com/7070711/72254391-cec06480-35fb-11ea-90d2-fb9c6f1c1a77.png)
will work for mvts. Should watch it in case need to allow some other unexpected values.

**Comment by dbauszus-glx** [comment]
I am pretty sure this was fixed. I remember adding a check on 0 in the themes but not sure when this had happened.
