### ISSUE TITLE
Multiple filters don't appear to be working

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#230]
Feature that was supposed to be testing 12th December but unfortunately no feedback was provided.

In /dev on the Retail Points later - filtering on Sainsburys, Tesco gives the following result

![mulitple filter on](https://user-images.githubusercontent.com/46957630/71831606-25301f00-30a1-11ea-8427-2714569f86d3.png)
[](url)

But removing the filter you can see that there should be a Tesco being displayed

![multiple filter off](https://user-images.githubusercontent.com/46957630/71831652-3bd67600-30a1-11ea-9c6d-98262550f719.png)

**Comment by dbauszus-glx** [comment]
What version is this? Filter work as expected using "sain, tesc" as test on current dev branch running the dev workspace locally.

**Comment by dbauszus-glx** [comment]
First screenshot also shows that you look for ' tesco' not 'tesco'. I will now remove leading whitespaces using .trim()

**Comment by lisataylor-geolytix** [comment]
I tried running locally and on geolytix.xyz/Dev didn't try part names though

**Comment by RobAndrewHurst** [comment]
Recreated the layer, and table in the xyz_test schema, and the test [instance](https://geolytix.xyz/test)

Having multiple delimited inputs on a filter seems to return correct results. 

![image](https://user-images.githubusercontent.com/43169158/72146974-3d0be980-33a6-11ea-8a79-dc16019cf096.png)

**Comment by dbauszus-glx** [comment]
Woah... what's that weird red line through the map though?

**Comment by RobAndrewHurst** [comment]
Running an output on the filter

**Comment by RobAndrewHurst** [comment]
![image](https://user-images.githubusercontent.com/43169158/72149854-bc9cb700-33ac-11ea-8b7f-a13f0a09fa91.png)

Odd clustering occurring when filtering on mab. Clustering returns to normal when removing the filter.

**Comment by RobAndrewHurst** [comment]
Current solution does not solve issue. Further investigation is required. Issue will remain open.

**Comment by RobAndrewHurst** [comment]
![image](https://user-images.githubusercontent.com/43169158/73333807-9ebbc700-4273-11ea-9b20-3c4339ae2df6.png)

This has been resolved in the latest version v2.1.1
