### ISSUE TITLE
type: integer displayed as 'NaN' when null.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#231]
![Screenshot 2020-01-07 at 16 26 51](https://user-images.githubusercontent.com/7070711/71906519-84a63180-316a-11ea-84c3-146f83b3e792.png)

Then zeros (as no isoline exists) are displayed.
This might be aftermath of iterating infoj in one go.
Falsy values should be skipped.

**Comment by dbauszus-glx** [comment]
Not falsy! Null values.

**Comment by dbauszus-glx** [comment]
I added a clause to continue in the _xyz.locations.view.infoj loop when entry is not editable (edit falsy) and value is null.

```
if (!entry.edit && entry.value === null) continue
```

This might have to be extended with some or || for the check on edit falsy.

Current test on an integer edit, non edit pairing.

null, show empty edit only.

![image](https://user-images.githubusercontent.com/22201617/71907960-0abf7980-3165-11ea-9058-1fe4965fced5.png)

0, show 0 in edit and non edit.

![image](https://user-images.githubusercontent.com/22201617/71907935-fbd8c700-3164-11ea-8f2e-ce963094c82b.png)

any other number, show number in edit and non edit.

![image](https://user-images.githubusercontent.com/22201617/71907999-1d39b300-3165-11ea-987d-bbdd7a9a700a.png)

Please test and assign back to me when there is a case where this doesn't work.

**Comment by RobAndrewHurst** [comment]
Tested, and seems to be acting as should. Will keep an eye for any odd behaviour with future data.
