### ISSUE TITLE
Graph/Table Toggle Issue

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#232]
When selecting multiple points, toggling the graph on/off will only toggle the graph/table in the last selected point.

![graph issue](https://user-images.githubusercontent.com/43169158/72048552-b384ea80-32c5-11ea-83ca-029d2040b37b.gif)

An example of this can be found at https://geolytix.xyz/test on the 'Workers' layer.

Currently deployed on latest dev : 85fc7f27be53912396a0bfa590bda1d8a40a07a4

**Comment by RobAndrewHurst** [comment]
It appears that the toggle issue is not restricted just to the graphs, but to catchment toggles as well.

![Peek 2020-01-09 15-33](https://user-images.githubusercontent.com/43169158/72071952-9bc55a80-32f5-11ea-9af2-461b7f522551.gif)

**Comment by RobAndrewHurst** [comment]
![Peek 2020-01-13 10-28](https://user-images.githubusercontent.com/43169158/72241469-9b77d880-35ef-11ea-8e97-dcfd08466b11.gif)

Toggling of different elements within injoj seems to be corrected. Will monitor for any returning issues.

**Comment by dbauszus-glx** [comment]
This feature was removed as the entry group logic has changed.
