### ISSUE TITLE
Polygon Geometry Checks

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#241]
The drawing interaction checks for valid geometries preventing self-intersections and such.

While technically correct the method also invalidates polygons with a single ring running counter clockwise. These will be validated during transformation and should be taken out of the geometry validation method.

**Comment by cityremade** [comment]
I will need to look at turf.kinks as this is the package that does the checks.

**Comment by cityremade** [comment]
Added flatten() on trail prior to self-intersection check. Please test whether it works ok.

**Comment by cityremade** [comment]
https://github.com/GEOLYTIX/xyz/issues/252

**Comment by dbauszus-glx** [comment]
This seems to work ok now.
