### ISSUE TITLE
Selected locations no longer working as accordions

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#246]
![Screenshot 2020-04-07 at 20 21 16](https://user-images.githubusercontent.com/7070711/78710500-583ab680-790d-11ea-92ec-9f4967189523.png)

when clicked on header they no longer expand/hide

**Comment by dbauszus-glx** [comment]
This is provisionally fixed by setting a maxHeight on the location view once added to the listview.

Please leave open for the time being. I feel there is a better solution and want to have a look at this with a fresh mind at some point.

**Comment by cityremade** [comment]
fixed.
