### ISSUE TITLE
Provide styles for tabs created with the tabview module

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#247]
![Screenshot 2020-04-07 at 20 22 38](https://user-images.githubusercontent.com/7070711/78710605-87e9be80-790d-11ea-8c19-25b6607fd764.png)
 
In this case it's unclear which tab belongs to which selection.

It should be possible to provide styles for the tab created with the tabview module.

**Comment by dbauszus-glx** [comment]
Done. This is a feature not a bug. The tabview is a control which must act independent from the location view.

A .tab_style css string property can now be provided to the dataview object input for the .add method of the tabview. The style will be applied to the tab element upon creation.
