### ISSUE TITLE
Conditional formatting not working on grouped columns

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#249]
I've just tried moving some columns into groups to allow more space for headers but the ability to have conditional formatting (e.g. red, amber, green) no longer works when columns are grouped

![image](https://user-images.githubusercontent.com/46957630/79383877-d9bdc480-7f5d-11ea-864a-c260604ba96f.png)

**Comment by dbauszus-glx** [comment]
Can we also look at the border styles. With grouped columns it is not pixel perfect.

![image](https://user-images.githubusercontent.com/22201617/79440515-00b3df00-7fce-11ea-832e-7ad98f63ccf1.png)

**Comment by cityremade** [comment]
Conditional formatter resolved - deep check on .columns array.

**Comment by cityremade** [comment]
![Screenshot 2020-05-13 at 16 20 44](https://user-images.githubusercontent.com/7070711/81831791-b45cb000-9535-11ea-9497-02fb600e124d.png)
Resolved.
