### ISSUE TITLE
Setting a cluster layer to only show at a certain zoom level breaks the infoj

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#253]
If i try to set a cluster layer to only show at a certain zoom level with

{tables}: "10": null,
               "11": tablename

then the infoj throws up the following error

![image](https://user-images.githubusercontent.com/46957630/79671432-20135d80-81c2-11ea-87f3-e66357aec1cb.png)

For now I've removed tables and replaced with table but it would be good to be able to only show cluster layers at certain zoom levels

**Comment by dbauszus-glx** [comment]
Looks like bad json syntax. Can you provide the complete tables entry as it is in the workspace.

**Comment by cityremade** [comment]
fixed. Multiple tables supported for cluster layers.
