### ISSUE TITLE
Cluster layers - layers with tables: {} not displaying

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#261]
Review tables: {} parameter for zoom layers. Says: relation undefined doesnt exist.
Example in blog workspace Riverford layer.

**Comment by dbauszus-glx** [comment]
This is impossible. Cluster are calculated based on the viewport. The zoom level is irrelevant for cluster. Unlike tiled layers where the extent of the tile is calculated from the zoom level. Selection on a cluster layer is based on the approximate distance of the cursor/touch to locations in the cluster table. This couldn't work with different tables. Selection must only provide a coordinate, not a zoom level.
