### ISSUE TITLE
File names for document upload

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#262]
Since changing to Cloudinary API library we seem to have lost the ability to get the resource filename.

**Comment by cityremade** [comment]
File name now works. Displays original file name, no problem uploading the exact same name, they are displayed oldest first.
![Screenshot 2020-05-12 at 12 13 51](https://user-images.githubusercontent.com/7070711/81679317-0d4f1a00-944a-11ea-8f8f-1f70019f1190.png)
