### ISSUE TITLE
Layer group toggle to toggle all on

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#270]
The layer group toggle turns any layer with display true off.

With all layers display: false the toggle is disabled.

The desired behavior is turn all layers on when the group toggle is switched on.

**Comment by cityremade** [comment]
The initial idea for group toggle was to prevent user from requesting all grouped layers at once.
Are you sure we want to pull loads of clusters in one go?

**Comment by dbauszus-glx** [comment]
Garbage in; Garbage out. There is nothing we can do against bad configurations. One cluster layer alone may break requests when a gazillion cluster are requested.

Being able to put a hundred cluster layers to be toggled simultaneously inside a single group isn't great but should not be forbidden. Performance can not happen by magic by requires knowledge of the inner workings and creating a set of layers which meet the requirements to turn a specific set of location data into information.

WIth a server, even worse a shared server it is not great if one configuration drags over processes down like a person drowning. In a serverless environment these processes stand alone and we / I don't care if process X dies because of an unreasonable amount of data requested.

Besides their are now fail saves such as request timeouts which will prevent crazy complex queries to block the data source layer and lock additional request pools until the end of times.

**Comment by cityremade** [comment]
Done.
