### ISSUE TITLE
Import / Export layer data

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#286]
Import and Export can be achieved with a custom post query.

**Comment by cityremade** [comment]
Download layer data as geojson implemented.

**Comment by dbauszus-glx** [comment]
Can you check whether the spooling, ie turning json into a file can be done in the client instead of the serverless function. We are trying to have serverless functions to process as little as possible. What can be done in the database should be done in the database and what can be done in the client should be done in the client.

With the file creation in the client it should also be possible to use the existing geojson endpoint without the need for the data endpoint which is almost identical to the geojson endpoint.

Can you also test whether it is possible to have the download / create file in a module a la cluster panel? This way we can customise the download per use case without having to ever change and test any core library code. This can also be an excellent showcase for client modules. I'll look at the client modules documentation today.

**Comment by cityremade** [comment]
I moved geojson download in the geojson endpoint. I made it straightforward but when we get client requirements for custom import/export this should be developed as a plugin.

**Comment by dbauszus-glx** [comment]
I have amended the layer download method. This should not require the geojson endpoint, changes to the geojson endpoint, or an infoj.

The download function should be based on the query method as it is used for dataviews. _xyz.query returns a response from query. _xyz.query supports viewport, filter, roles, etc.

All which was needed was spooling the response from _xyz.query to a file (blob).

Definition for the download should be as follows.

"download": {
  "query": "blueprint_json",
  "format": "json"
}

The download object is passed to the query method and supports viewport, filter, roles, etc.

The download link can be created like so:

```javascript
    _xyz.query(layer.download).then(response => {

      const blob = layer.download.format === 'json' && blobJson(response) || blobCSV(response)
     
      const link = _xyz.utils.html.node`<a
        href=${URL.createObjectURL(blob)}
        download=${`${layer.key}.${layer.download.format || 'csv'}`}>`

      link.click()

    })
```

And the blob functions for CSV and JSON are like this:

```javscript
  function blobJson(response) {

    const rows = response.map(record=>{

      const feature = {
        type: 'Feature',
        properties: record
      }

      feature.geometry = JSON.parse(record.geometry)

      delete feature.properties.geometry

      return feature

    })

    const json = JSON.stringify({
      type: 'FeatureCollection',
      features: rows
    })

    return new Blob([json], {type: 'application/json'})
  }

  function blobCSV(response) {

    const rows = response.map(record=>{

      return Object.values(record).map(record => {

        return isNaN(record) && `"${record}"` || record

      }).join(',')
    })
    
    const csv = rows.join('\r\n')

    return new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  }
```

note: The geometry field for the geojson must be defined as geometry in the query.

eg.
```json
"blueprint_json": {
  "template": "SELECT id, name, address, st_asgeojson(geom_p_4326) as geometry FROM mapp.points WHERE true ${viewport}",
  "dbs": "MAPP"
}
```
