### ISSUE TITLE
Dot Symbols

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#295]
The svg dot symbol for cluster layer does not seem to be working.

**Comment by cityremade** [comment]
![Screenshot 2020-07-28 at 09 51 15](https://user-images.githubusercontent.com/7070711/88642060-e6eb6300-d0b7-11ea-92c7-888c8ab532c0.png)

Dots show up, the settings below:

`"style": {
      "default": {
           "type": "dot",
           "fillColor": "#ffb300"
       },
       "cluster": {
             "type": "dot",
             "fillColor": "rgba(0, 75, 168, 0.3)",
             "scale": 2,
             "size": 30
        },
        "highlight": {
              "scale": 2.1
        }
}`
