### ISSUE TITLE
Configuration for external gazetteer

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#298]
The gazetteer configuration was built up from Google Autocomplete. Configuration is then translated from the Google Specification for other external services such as Mapbox. Code for example is translated to Country.

This was a terrible idea by myself. We should not translate but use the original specification as outlined in the individual guides.

We should create a the query string from a configuration object and include everything in this configuration object not just a selected few keys.

**Comment by cityremade** [comment]
Google
countrycode
components (see API docs, used for search across selected countries, eg. UK + IE)
bounds

Mapbox 
country
bounds

Open Cage
countrycode
bounds
