### ISSUE TITLE
Setting an editable numeric field to ''

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#304]
PostgreSQL updated statements like this are invalid on integer fields.

```
UPDATE schema.table SET  field = '' WHERE id = $1;
```

Removing the value from the edit input of a numeric field must set the new value to NULL, not '' or 0.

**Comment by cityremade** [comment]
@RobAndrewHurst can you test if it works ok? I fixed it in the past several times.

**Comment by cityremade** [comment]
tested and works. Both integer and numeric.
