### ISSUE TITLE
Different geometries for different zoom levels

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#310]
While it is possible to define different tables for different zoom levels in the layer tables configuration it is currently impossible to define different geometries for different tables, or indeed the same table with different geometry fields.

It should be possible to define a geometry field with a table in the tables configuration to support multiple geometry fields. This will allow to have simplified geometries for the same location at lower zoom levels.

It would be possible to define the geometry field separated by a pipe or other symbol which cannot be part of a regular table or field name.

**Comment by fazzer14** [comment]
5 stars if this is solved

**Comment by dbauszus-glx** [comment]
This is no possible by defining a geoms object in similar fashion to the tables array. Obviously null won't do anything in this object. 

```
{
  "locales": {
    "UK": {
      "bounds": {
        "north": 62,
        "east": 5,
        "south": 49,
        "west": -13
      },
      "minZoom": 2,
      "maxZoom": 17,
      "maskBounds": true,
      "showScaleBar": true,
      "layers": {
        "ZoomGeom": {
          "display": true,
          "format": "mvt",
          "geom": "geom_3857_5m",
          "srid": "3857",
          "dbs": "MAPP",
          "qID": "id",
          "geoms": {
            "7": "geom_3857_100m",
            "8": "geom_3857_50m",
            "9": "geom_3857_50m",
            "10": "geom_3857_5m",
            "11": "geom_3857_5m",
            "12": "geom_3857"
          },
          "table": "geodata.uk_glx_geodata_seamless_shopper_town"
        }
      }
    }
  }
}
```

The geom will be determined in the mvt mod.

```
  const geoms = Object.keys(layer.geoms)

  var geom = geoms && layer.geoms[z] || layer.geom

  var geom = geoms && z < parseInt(geoms[0]) && Object.values(layer.geoms)[0] || geom
  
  var geom = geoms && z > parseInt(geoms[geoms.length -1]) && Object.values(layer.geoms)[geoms.length -1]  || geom
```

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/commit/43dbab1d93bed30a8b24ed613c71e28e11aa5150
