### ISSUE TITLE
Cluster styles

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#314]
Location or cluster of locations on a cluster layer may only be represented by a symbol.

This symbol for location and cluster is currently defined by marker and markerMulti respectively. Each of these are a style object similar to the default / highlight style used for non-cluster layer.

There is a scale property which is used to scale a symbol.

There are markerMin/Max settings which can be defined inside the marker, markerMulti, and theme styles.

The markerMin and markerMax define the size range symbols. A single location will be drawn at the size of markerMin. A cluster will be drawn at a size according to the ratio of locations inside the cluster against the largest cluster in the viewport. The largest cluster in the viewport will be drawn at the markerMax size.

marker definitions are exactly the same as a default style definition for other types of layer. marker should be renamed to default to be in line with other layer style definitions.

markerMin needs to go. markerMin being the size of a single location. scale and size should be added to the default style and any other symbol styles.

Openlayers only understands scale to scale a symbol. Size should be introduced in addition to scale. Size should be defined as pixel. The size should be the average of width and height of a symbol. The size can then be used to scale a symbol.

markerMulti should be renamed to cluster as it only applies to cluster. The scale / size inside the cluster is the maxSize.

This allows for locations to be defined as default, cluster, in a theme, or as highlight.

Object assign applies in this order.

The default style will be applied to single locations.

The cluster style will be assigned to the default style for cluster. As a minimum we only need to define a scale or size in the cluster.

A theme style will either be applied to the default or default + cluster style for graduated themes or if all locations in a categorized theme are of the same type.

The highlight style will be assigned to the previously created style for when a location of cluster is highlighted. As a minimum we only need to set a scale or size in the highlight style.

**Comment by dbauszus-glx** [comment]
An example style would be:

```
style: {
  default: {
    svg: 'https://...',
    size: 20
  },
  cluster: {
    size: 50
  },
  highlight: {
    scale: 1.2
  }
```

I would expect this style to work with a cluster as well as with an mvt layer. The mvt layer would just ignore the cluster style.

On a cluster layer I would expect the same symbol to be used for locations and cluster of locations.

A location symbol would be sized 20 pixel and the biggest cluster would be sized as 50 pixel. Cluster in between would be sized according to the ratio. Lets say the biggest cluster of 50 locations is sized at 50 pixel. A cluster of 25 locations should be sized 35pixel, half between 20 and 50 pixel.

A highlighted symbol should be 20% bigger than the original symbol for either location or cluster.

I would like for scale or size or both to work in either style definition.

**Comment by cityremade** [comment]
`marker` renamed to `default.` _I kept `marker` property in mvt/geojson styling though._
`markerMulti `renamed to `cluster`. 

`cluster` inherits `default` but gets `scale: 1.2` to make it slightly larger. Parameters can be overridden if style distinction is needed. 

`highlight` inherits previous values but gets default `scale: 1.3` - please note scale on highlight is slightly higher to prevent scaled icon from shrinking on interaction.  

All styling can have `size `value and will grow proportionately for clusters, but `layer.style.cluster.size` is the maximum value cluster size can get. Default => `size: 20`

`scale` is now a friendlier number. Defaults to 1, can be set to anything.

Let me know how this works out and if any improvement is needed. 

All added to docs.

**Comment by dbauszus-glx** [comment]
Cluster styles have now a property clusterScale. The default is 2. The clusterScale defines the size which is applied to the largest cluster in the mapview.
