### ISSUE TITLE
Query modules

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#316]
Modules may now be imported dynamically.

This is obviously extremely experimental and wants some testing.

```
    "n_from_table": {
      "module": "https://geolytix.github.io/public/n_from_table.js"
    }
```

Setting a module location will import this module as a template.

Template modules must have a render method defined.

```
module.exports = {
  render: _ => {

    const n = _.n * 2

    return `select * from ${_.table} limit ${n}`
  }
}
```

The "import" is done by creating a module from the module constructor using the response as source and the url as filename.

```
      if (entry[1].module) {
        return provider.http(entry[1].module)
        .then(response => {

          const Module = module.constructor;
          const m = new Module();
          m._compile(response, entry[1].module)
          _resolve(m.exports)

        })
      }
```

**Comment by cityremade** [comment]
Tested on dev workspace with postal and oa boundaries. Need for a use case on production.

**Comment by cityremade** [comment]
Done and used on live app.

**Comment by dbauszus-glx** [comment]
Due to the introduction of parameter substitution in the src string it was necessary to change module for src.

The module still needs to be constructed and the type must be defined either as 'module' = true, or 'type' = 'module'.

This allows to catch error when fetching the module from src. This allows also for modules to be provided from different src types.

**Comment by cityremade** [comment]
added to docs.

**Comment by cityremade** [comment]
Added to docs, we have it working on live app. Closing.
