### ISSUE TITLE
Support JSON field in infoj

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#318]
I would like to have a JSON type field which will be parsed and stored as a JSON type field in the PostGIS layer. There need to be checks on the input that the field contains valid JSON.

Once this is working the JSON type field should replace the meta type field. Allowing a JSON type field to be used as meta data field or indeed for any other type of configuration. We already have enough controls to hide or style the field in the location view.

**Comment by cityremade** [comment]
Replace "meta" with new "json" type.

**Comment by cityremade** [comment]
Complete.
