### ISSUE TITLE
Tooltip for geometry properties / metrics / measure

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#321]
Setting the tooltip key of a editable geometries to either area, distance, or length will produce a tooltip popup on the mouse cursor during the construction in the draw interaction.

```
          "edit": {
            "polygon": {
              "tooltip": "length"
            },
            "freehand": true,
            "circle": {
              "tooltip": "distance"
            },
            "rectangle": {
              "tooltip": "area"
            },
            "line": {
              "tooltip": "length"
            },
            "isoline_mapbox": true,
            "isoline_here": true,
            "delete": true,
            "geometry": true
          },
```

This metrics are calculated with [openlayers sphere methods](https://openlayers.org/en/latest/apidoc/module-ol_sphere.html).

The distance is calculated from the interiorPoint of the geometry to the mapview.position (cursor).

Length is measured along the geometry. For polygons, circles, and rectangles the length is the circumference.

**Comment by dbauszus-glx** [comment]
I made the layer param optional for the draw action. This allows to draw temporary geometry. The context menu will not be shown and the geometry will be cleared if the interaction is finished.

This allows for measure tools to be built like so in the desktop view.

```
    document.querySelector('.btn-column').appendChild(xyz.utils.html.node`
      <button
        title="Measure distance"
        onclick=${e => {

          if (e.target.classList.contains('enabled')) return xyz.mapview.interaction.draw.cancel()

          e.target.classList.add('enabled')

          xyz.mapview.interaction.draw.begin({
            type: 'LineString',
            tooltip: 'length',
            callback: () => {
              e.target.classList.remove('enabled')
            }
          })
        }}><div class="xyz-icon icon-line off-black-filter">`)   
```

**Comment by cityremade** [comment]
Added to docs.
