### ISSUE TITLE
Drawing order for layer

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#326]
Location geometries should always be drawn on top.

![image](https://user-images.githubusercontent.com/22201617/88302558-e5a7e800-ccfd-11ea-863a-5dd68dbeba53.png)

**Comment by cityremade** [comment]
The above results from fact that both layers are drawn on the same zIndex, while additional geometry is drawn just below source location.
While layers are by default drawn on zIndex = 1, cluster layer will now be drawn by default on zIndex = 10, unless set otherwise  as `layer.style.zIndex`.

**Comment by cityremade** [comment]
Added to docs.
