### ISSUE TITLE
Multiple datasets in charts

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#327]
Previously we could only get data from a single object into charts. If multiple datasets where to be drawn field names had to be used for the different datasets.

The getData function will no check whether the response is an array. This uses the capability to pass the index into the map function which returns the data from the response into an array of datasets.

```
function getdata(dataset, i) {
  
  const responseDataset = response[i] || response
  
  if (dataset.fields) {
    return dataset.fields.map((field) => responseDataset[field] && responseDataset[field])
  }
  
  if (dataset.field) {
    return responseDataset[dataset.field]
  }
  
  return responseDataset
}
```

**Comment by cityremade** [comment]
Chart.js's own datasets property is an array. If there's one dataseries it's an array of 1.

2-dataset test query I am using:

`SELECT id AS id, random1 AS random1, random2 AS random2, random3 AS random3, random4 AS random4, random5 AS random5, random5 AS rev_random1, random4 AS rev_random2, random3 AS rev_random3, random2 AS rev_random4, random1 AS rev_random5 FROM dev.uk_glx_sites WHERE id = ${id};`

Then some fields go into respective series in configuration.

`"datasets": [
                            {
                                "fields": ["random1", "random2", "random3", "random4", "random5"],
                                "label": "Serie 1",
                                "type": "bar"
                            },
                            {
                                "fields": ["rev_random1", "rev_random2", "rev_random3", "rev_random4", "rev_random5"],
                                "label": "Serie 2",
                                "type": "line"
                            }]`

Any more details on this?
