### ISSUE TITLE
Prevent click propagation for ol-control

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#328]
At the moment when map uses zoom control buttons click results in selecting feature underneath. 
Click propagation from .ol-control container should be stopped.

**Comment by dbauszus-glx** [comment]
I'll have a look at this when I look at native events for highlight and select.

**Comment by dbauszus-glx** [comment]
This issue should be resolved by using native methods e,g, map.on(mousemove), map.on(click) instead of adding eventlistener to the mapview node.
