### ISSUE TITLE
Selection and Themes

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#337]
Currently the selection requires a **qID** field and an **infoj** array. Without an **infoj** field, selection will err. But without an **qID** field themes will err.

A qID field should be added to themes for layers with locations which should be styled by theme but not selectable.

**Comment by cityremade** [comment]
I tested it with mvt and cluster layers. If qID is unset themes will be applied with no ability to select so this works fine.

What happens in case of defined qID and undefined infoj? It'd make sense to disable selection but allow highlight/hover.

**Comment by cityremade** [comment]
Updated docs.
