### ISSUE TITLE
Show default style in header

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#341]
The default icon will no longer be rendered by default in the layer view header.

A showInHeader flag can be added to the default style.

```
"style": {
  "default": {
    "showInHeader": true,
    "type": "dot",
    "fillColor": "#E51636",
    "scale": 1
  }
}
```

This supports icons only at the moment but could be expanded to show polygon and line styles as well.

**Comment by cityremade** [comment]
Added to docs.
