### ISSUE TITLE
Styling on Numbered Clustering 

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#342]
Styling on numbered clustering seems to be incorrect.

**The number seems to be just off centre.**

![image](https://user-images.githubusercontent.com/43169158/91972344-dd8a9180-ed1a-11ea-84c9-acfbb9a55967.png)

![image](https://user-images.githubusercontent.com/43169158/91972382-f2672500-ed1a-11ea-9d4f-740dd0a4c97c.png)

**Comment by cityremade** [comment]
done, fixed target icon radius.
