### ISSUE TITLE
CDN Workflow 2.0

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#343]
## Revised Workflow

Revised workflow has created the need to create a separation of the CDN domain used in a workspace, so that we can make use of different AWS CDN domains. That way we can point different instances to different s3 buckets, that are referring to different branches in the same repo.

Example of `.env` making use of `CDN_DOMAIN`

```
 "TITLE": "GEOLYTIX XYZ | Test",
    "DIR": "/test",
    "ALIAS": "geolytix.xyz",
    "PRIVATE": "",
    "SECRET": "",
    "APPROVAL_EXPIRY": "30",
    "CDN_DOMAIN": "blag.cdn.com"
    "TRANSPORT": "",
    "WORKSPACE": "",
    "DBS_MAPP": "",
    "KEY_GOOGLE": "",
    "KEY_HERE": "",
    "KEY_MAPBOX": ""
  }
```

Example of Workspace using `CDN_DOMAIN` KEY

```
{
  "templates": {
    "test_template": {
      "src": "{CDN_DOMAIN}/path/to/s3oject.json"
    }
} 
```

This can accommodate for the new workflow

![Workflow (1)](https://user-images.githubusercontent.com/43169158/92388924-583b1e80-f118-11ea-9b09-e7d0d380b864.png)

**Comment by dbauszus-glx** [comment]
I added parameter substitution for ${SRC_*} in the workspace.

These will be substituted in the src key of templates:

```
      entry[1].src = entry[1].src.replace(/\$\{(.*?)\}/g,
        matched => process.env[`SRC_${matched.replace(/\$|\{|\}/g, '')}`] || matched)
```

Or anywhere in the locales, e.g. in SVG src strings.

```
  workspace.locales = JSON.parse(
    JSON.stringify(workspace.locales).replace(/\$\{(.*?)\}/g,
      matched => process.env[`SRC_${matched.replace(/\$|\{|\}/g, '')}`] || matched)
  )
```

In the environment parameters these have to be defined as SRC_*. The * must match the parameter in the ${*} in the workspace value.

**Comment by dbauszus-glx** [comment]
https://geolytix.github.io/xyz/docs/environment-settings/#src_*-parameter
