### ISSUE TITLE
Language - use selected language from url in case no user is found

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#349]
![Screenshot 2020-09-29 at 20 39 55](https://user-images.githubusercontent.com/7070711/94607531-f0e63980-0293-11eb-84be-6e529aa224e4.png)

token.js, no user check

**Comment by dbauszus-glx** [comment]
That one is fixed.

The login forms where missing the language input which sends the language key in the body.

![image](https://user-images.githubusercontent.com/22201617/94667843-38f27400-0307-11eb-92b7-e689d5374c7b.png)

**Comment by cityremade** [comment]
Works.
