### ISSUE TITLE
Use language as role

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#350]
![Screenshot 2020-10-07 at 13 29 22](https://user-images.githubusercontent.com/7070711/95330906-1df0a880-08a1-11eb-9b54-043abef01f37.png)

At the moment objects require roles for all supported languages in order to be displayed when selected language version is not available.

**Comment by dbauszus-glx** [comment]
This can be solved by reverse roles.

Reverse roles should be prefixed with ! just like regular JS clause reversal.

User A roles are [JP, KR].

User B roles are [DE, ES].

User C roles are [EN].

Tests

[JP]; User A

[EN]; User C

[EN, !JP]; User B & C

[!JP]; User B & C

[EN, DE]; User B & C

This can be done by adding following line to the role check:

```javascript
  locale.layers = Object.entries(locale.layers)
    .map(layer => {

      if (!layer[1].roles) return layer[0]

      // check whether the layer is available for roles in token.
      if (Object.keys(layer[1].roles).some(
        role => req.params.token && req.params.token.roles
          && req.params.token.roles.includes(role)
          || (role.match(/^\!/) && !req.params.token.roles.includes(role.replace(/^\!/, '')))
      )) return layer[0]
    })
    .filter(layer => !!layer)
```

The key is to check whether a role starts with an exclamation mark `match(/^\!/)`; And if so check whether that role is not included with the exclamation mark removed from the role `!roles.includes(role.replace(/^\!/, ''))`

**Comment by cityremade** [comment]
so if I want to show a japanese layer to a japanese user I write on it
` ja: true`
but not show the equivalent english layer then on the english layer:
`!ja: true`
?

**Comment by dbauszus-glx** [comment]
Yes.

I added this to the last commit but for layer in get workspace only. https://github.com/GEOLYTIX/xyz/commit/7861bb231153d849ffdc01b959e0ea4228af61d5

**Comment by dbauszus-glx** [comment]
You have two ways to control... Either list all the roles for which an object should pass or list a reverse role which should pass if the role is not found.

This way that role can even have filter. It's not specific to languages but should apply to any form of role.

**Comment by dbauszus-glx** [comment]
For example:

```json
      "layers": {
        "Mapbox Base JP": {
          "template": "Mapbox Base",
          "roles": {
            "jp": null
          }
        },
        "Mapbox Base Not JP": {
          "template": "Mapbox Base",
          "roles": {
            "!jp": null
          }
        },
        "Mapbox Base": {
          "display": true,
          "template": "Mapbox Base"
        }
      }
```

Mapbox Base will always be seen by anyone. Logged in to English or Deutsch I see the Base and Not JP layers. Logged in to Japanese I see the Base and JP layer, but not the 'Not JP' layer.

**Comment by cityremade** [comment]
added to docs.
