### ISSUE TITLE
Labelling hidden beyond certain zoom level

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#351]
Sometimes it's useful to hide labels when they no longer contribute to map story.

**Comment by dbauszus-glx** [comment]
Agreed... There should be `zoomMax: int` in the configuration object for label.

This should disable the checkbox input.

A conditional check should be added where the display property of the label object is checked.

**Comment by dbauszus-glx** [comment]
Label now support minZoom, maxZoom, as well as title.
