### ISSUE TITLE
Using Ol polyline decoder for here api v8 polylines

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#359]

**Comment by cityremade** [comment]
Polyline from here API 

`BGm0mskDi55gDwVkQ8qB8qB4KmgBAwhI3KmgBtVwV3KmgBA8qB1KmgBvVwV1KmgBA61C3KmgBtVuV3KmgBA-qB3KmgBtVuV3KmgBA61C1KmgBvVwV1KmgBA8qB3KmgBtVwV3KmgBA-lgB3KmgBtVuV3KmgBAwnoB1KmgBvVuV1KmgBAunoB3KmgBtVwV3KmgBAunoB3KmgBtVuV3KmgBA-tR4KmgBuVuVwVsgCuVuVuVsgCwVwVuVsgCuVuV4KmgBA-qB4KkgBuVwV4KmgBA0rF3KmgBtVwV3KmgBA8qB3KmgB51C81ClgB2K9qBAlgB4K1KmgBAssJ2KmgBwVwV2KmgBAy2G4KmgB-qB-qBmgB2K-iQAmgB4KwVuVmgB4K4gEAmgB3K8qB7qB4KlgBA9qB4KlgBuVtV4KlgBA9qB2KlgBwVtVuVrgCuVvVwVrgCsgCrgCuVrgCuVtV4KlgBA7qB4KlgBuVvV4KlgBArsJ3KlgBtVvV3KlgBAx2G4KlgBuVtVuVrgC-qB9qBmgB1K61CAmgB2K61C81C4KmgBA8qB4KmgBuVwV4KmgBAssJ2KmgBwVAuVrgCuVtVwVrgC4gE3gEmgB3K61CAmgB4K8qB8qB4KmgBA-qB4KmgBuVuV4KmgBA81C2KmgBsgCsgC4KmgBAuhI3KmgBtVwVtVsgCrgCuVvVuVrgCwV7qB8qB3KmgBA-qB1KmgBvVuVtVsgC9qB-qBlgB4K7qBAlgB2KAwVsgCsgC2KmgBAuhI1KmgBvVwV1KmgBA4gE3KmgB51C61ClgB4K1rFAlgB3KtVtVlgB3K51CAlgB3KvVtVlgB3KniMAlgB4K1KmgB2KmgBwVuV2KmgBAwhI1KmgBvVuVtVsgCtVwVvVsgC51C61ClgB4K51CAlgB3KtVtVlgB3K1rFAlgB3KtVtVlgB3K54SAlgB1KvVvVlgB1KrsJAlgB3KtVtVlgB3K1rFAlgB3KtVtVlgB3Kz2GAlgB1KtVvVlgB1Kh4OAlgB3KtVtVlgB3K51CAlgB3KvVtVrgCtV7qB9qBvVrgC7qB7qBlgB3K9qBAlgB3KrgCrgCrgCtV9qB9qBtVrgCtVtV3KlgBA3gE3KlgBtVtVtVrgCvVvV1KlgBA51C3KlgBlgB1KlgB2KjhGkhGrgCuVl2Eo2ElgB2K51CAlgB1K51C71C3KlgBA51C3KlgBrgCtVtVrgCtVvV3KjgBAvhI4KlgB4gE3gEkgB3K-qBAmgB4KqrDorDmgB4KmgB3Km2El2EsgCtV-qB9qBuVrgCuVtVwVrgCsgCrgC2KlgBA9qB4KlgBuVtVAtVtVvVtVrgCvVtV1KlgBAx2G2KlgBwVvVuVpgCsgCvVuVtVsgCtVAvVtVtV3KlgBAvhI4KlgB61C51CsgCvVuVrgCmgB1K2rFAmgB3KuVtVmgB3K4gEAmgB4KsgCsgCsgCuVuVsgCwVuV2KmgBA02G1KmgBvVuVAuVsgCsgCwVsgCuVwVuVqgCwVwVuVsgCuVuVwVsgC8qB-qBsgCuVwVuVmgB4K8qBAmgB3KuVrgCwVtVuVrgC-qB9qBmgB1K61CAmgB2K61C81C4KmgBA8qB4KmgBuVAuVtVmgB3K-qBAmgB4KuVuVmgB4K81CAmgB4KorDorDsgCwVm2Em2EwVA61C51C4KlgBA_iQ2KlgBwVtV2KlgBAx8mB4KlgBuVtV4KlgBAtvZ3KlgBlgB1KzrFAlgB3K9qB9qBtVrgCvVtV1KlgBA1rF2KlgBwVtVuVrgC61C51CmgB3K81CAmgB1KuVvVsgCtV4KlgBAjwd3KlgBtVvVvVrgCtVtV3KlgBAvhI4KlgBqrDnrD2KlgBAh7e4KlgBuVtV4KlgBAvkY4KlgBuVtV2KlgBA71C4KlgBuVtV4KlgBA9qB4KlgBuVtV4KlgBA51C2KlgBwVtV2KlgBA9qB4KlgBuVtV4KlgBA71C4KlgBuVtV4KlgBA9qB2KlgB81C51CmgB3K61CAmgBsFuVmgB`

**Comment by dbauszus-glx** [comment]
https://isoline.router.hereapi.com/v8/isolines?apiKey={key}&range[type]=time&range[values]=600&destination=52.5308,13.3847&transportMode=car

**Comment by dbauszus-glx** [comment]
I added the Here Polyline as a module to the utils.

https://github.com/GEOLYTIX/xyz/blob/development/lib/utils/herePolyline.mjs

`xyz.utils.herePolyline.decode('BFoz5xJ67i1B1B7PzIhaxL7Y')`
