### ISSUE TITLE
Prevent SQL injection in MVT fields

### ISSUE THREAD

**Issue by chriszrc** [GEOLYTIX/xyz#36]
Really great looking project here, could really make it a lot easier for people to start using mvt tiles with postgis. One question though in:

https://github.com/GEOLYTIX/xyz/blob/master/mod/mvt.js

I see parameters information from the express route being used directly in the sql string literal, and as far as I can see, no attempt at escaping characters in the values, etc. I ended up with the same problem implementing this in my app, I'm curious if there's a good solution for this out there-

**Comment by dbauszus-glx** [comment]
@chriszrc 

The master is ancient. We plan to update master after the documentation is more complete.

We do check for SQL injection on the field names.

https://github.com/GEOLYTIX/xyz/blob/dev/mod/mvt.js

Only if a field is in the app settings it is validated.

We also do now cache the tiles in second postgis table which is referenced in the settings.

Compare:

https://geolytix.xyz/open/mvt/9/255/172?dbs=XYZ&table=glx_cities_of_the_world&qID=id&properties=pop_density,&layer=sprawls&geom_3857=geom_3857&tilecache=glx_cities_of_the_world__tc

With:

https://geolytix.xyz/open/mvt/9/255/172?dbs=XYZ&table=glx_cities_of_the_world&qID=id&properties=DROP%20TABLE;,&layer=sprawls&geom_3857=geom_3857&tilecache=glx_cities_of_the_world__tc

You can see the tile caching in action here:

https://geolytix.xyz/open/?locale=Global&layers=base,label,sprawls&lat=0&lng=0&z=3

The master has also bad cluster and no real mvt styling.

I am planning to do a writeup on MVT next month. Version 1.0 press is anticipated prior to FOSS4G in Dar. I also have an abstract for workshop and presentation there. Fingers crossed.
