### ISSUE TITLE
Test object.assign on chart datasets

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#369]
merge query + datasets options

**Comment by dbauszus-glx** [comment]
Is this something I can look at? What is the bug? Is there an error exception to work with?

**Comment by cityremade** [comment]
just about to test it. when datasets are defined in chart setup they should be assigned into respective datasets returned from the query, such as fillColor for specific series etc.

**Comment by cityremade** [comment]
![Screenshot 2020-12-10 at 14 23 43](https://user-images.githubusercontent.com/7070711/101784354-50ae5b80-3af3-11eb-8459-7a0999581322.png)
ok, works as it should 👍
