### ISSUE TITLE
Distance metrics - circle draw metric tooltip returns distorted length.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#376]
![Screenshot 2020-12-18 at 13 00 29](https://user-images.githubusercontent.com/7070711/102617381-02bbd800-4131-11eb-96af-052cf28cf930.png)

Purple circle was constructed from turf with 4326 centre coordinates and radius of 3km.

When using custom radius plugin where feature is constructed with turf.circle measured radius is correct.
When similar circle is drawn with interaction distance metric tooltip returns significantly distorted value.

Problem possibly lies with the fact that ol length() inside metrics function is calculated from 3857 coordinates.

**Comment by dbauszus-glx** [comment]
Distances need to be measured through ol.sphere not taken from getLength of the metric geometry.

```js
      distance: () => ol.sphere.getLength(new ol.geom
          .LineString([geometry.getInteriorPoint().getCoordinates(), _xyz.mapview.position]))
```
