### ISSUE TITLE
Geometry disappearing on MVT layer while dragging

### ISSUE THREAD

**Issue by wmattei** [GEOLYTIX/xyz#392]
I understand that the points on the map need to disappear while dragging and zooming for perfomance reasons,  but i think it would be good if it was optional, i've commented out the lines of code that do that and it worked perfectly in my scenario.

**Comment by dbauszus-glx** [comment]
This should now be resolved by using a custom load strategy which creates a new source overwriting the existing source once all the data is loaded from the endpoint.
