### ISSUE TITLE
api/location without fixing id

### ISSUE THREAD

**Issue by Kaziz94** [GEOLYTIX/xyz#415]
Is it possible to use api/location/get without id in v3.5.2 like api/location/select/aggregate in other version ?
see: https://geolytix.gitbook.io/xyz-developer-guide/routes/api/location/select/api-location-aggregate

And what are the differences between the versions of xyz (main, v2_master, v1_master) ?

Thanks.

**Comment by dbauszus-glx** [comment]
Version 1 was build with Leaflet as map library.

Version 2 was build with Openlayers as map library.

Version 3 (current main) is build with Openlayers as map library and the backend is optimised to be deployed as a serverless function via Vercel.

Version 4 (snowpack branch) will retire webpack as build tool in favour of snowpack. UI components will be taken out of the mapp library and put in a seperate ui library. The library will no longer require to be initialised for a single mapview but multiple mapviews are supported by one instance of the library. Plugins can be imported as ES6 modules. There will be more configuration options for the front end and back end.

In regards to api/location/select/aggregate this will not be possible with current versions. This should be done with a custom module for the XYZ host. We don't want to have very specific configurations in the workspace in favour of configurable plugins for the frontend and modules for the XYZ host. Once v4 goes into beta we will be skimming through all the plugins and modules which have mostly been written for client applications and aim to generalise these bits of code for a range of samples.

**Comment by dbauszus-glx** [comment]
Please note we abondened gitbooks in favour of github pages.

https://geolytix.github.io/xyz/docs/
