### ISSUE TITLE
Ability to override default app view

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#422]
Linked to [#421 ](https://github.com/GEOLYTIX/xyz/issues/421)

At the moment we can't replace default app view with a custom view

Add support to this behaviour where app takes custom view as the default app view:

[https://geolytix.dev/vaxx](https://geolytix.dev/vaxx)

**Comment by dbauszus-glx** [comment]
This should work.

The lookup names for the default views are in the [view dictionary for templates](https://github.com/GEOLYTIX/xyz/blob/development/mod/templates/views.js).
