### ISSUE TITLE
GeoJson Not Currently Displaying

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#423]
GeoJson layers are not currently rendering.

Investigating to see what the issue is.

**Comment by RobAndrewHurst** [comment]
Features coming through to OL are Undefined

**Comment by dbauszus-glx** [comment]
GeoJSON should work with this commit.

https://github.com/GEOLYTIX/xyz/commit/090b72c1ac939b9625a7579c51d34cd9556ad3c1

There is quite a lot happening though. GeoJSON layer do not support filter or themes. The idea is that a GeoJSON layer is loaded in it's entirety when first requested and the data being cached. The layer.reload method will force a reload of the data.

**Comment by RobAndrewHurst** [comment]
Fixed and working!
