### ISSUE TITLE
Mismatch between pin location and input location for generated isolines.

### ISSUE THREAD

**Issue by jfitzpatrick17** [GEOLYTIX/xyz#426]
Here Isoline - when you click on the map to run a drive or walk time, the marker ('A') appears at a completely different location to where you have clicked on the map

**Comment by dbauszus-glx** [comment]
Previously it was not possible to control the marker location. This can be controlled with v4. It should be possible to have the pin on the click geometry.

**Comment by dbauszus-glx** [comment]
This has been solved by design.

A pin location can be defined as a `type: pin` entry in the infoj.

A isoline can be generated on a point with `type: isoline_mapbox` or `type: isoline_here`.
