### ISSUE TITLE
Map Module

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#43]

**Comment by dbauszus-glx** [comment]
The map modules (leaflet, gl, openlayers) sit in their respective public js folders and are bundled to be directly imported from a deployment.

The leaflet control in the _mapp_ interface should be updated to use the es6 entry used for bundling the leaflet control.

**Comment by dbauszus-glx** [comment]
The XYZ control is now a bundle which takes in some files from a Leaflet folder to be replaced with OpenLayers in the future.
