### ISSUE TITLE
User Admin - Default roles for new user

### ISSUE THREAD

**Issue by jfitzpatrick17** [GEOLYTIX/xyz#430]
**Summary**
Currently users can be approved without being assigned a user role, resulting in them seeing a blank interface when they login

**Desired outcome**
Admin users should be prompted to assign a user role as part of account approval. This will only be relevant to instances with user roles.

**Comment by dbauszus-glx** [comment]
This should be controlled in the ACL schema.

The roles field is defined like so:

`roles text[] default '{}'::text[],`

The default should include the roles to be assigned for new users in that ACL.
