### ISSUE TITLE
User Admin - Option to 'filter out' email address domains

### ISSUE THREAD

**Issue by jfitzpatrick17** [GEOLYTIX/xyz#433]
**Issue**
The admin console can get quite cluttered when there is a high number of users.

**Desired outcome**
Option to 'filter out' or 'hide' certain domains from the admin panel

**Comment by dbauszus-glx** [comment]
There is now a filter input in the admin view which filters out user where either the email address or some role includes the search term. https://github.com/GEOLYTIX/xyz/commit/f6132a3ddcae554a5f87355deb8b991535db0064
