### ISSUE TITLE
Flatpicker parameters not included

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#449]
when parameters are set in flatpicker options:

enableTime
defaultHour
defaultMinute

they are not taken into account when flatpicker is initialized.

In the beginning I spotted hour/minute selection container to be invisible.

https://flatpickr.js.org/options/

**Comment by dbauszus-glx** [comment]
Should be resolved here https://github.com/GEOLYTIX/xyz/commit/6849ee3305f96d87c788098083a807398688058c

I bumped flatpickr to 4.6.9.

And updated the flatpickr scss with matching stylesheet provided [here](https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.css).
