### ISSUE TITLE
location view elements that are hidden don't render on map view

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#451]
Elements that are hidden in the infoj (location view) don't render on the mapp. Below is an example of said configuration.

```json
{
      "title": "Here's tomtom",
      "name": "TomTom Reachable Range",
      "display": true,
      "hidden": true,
      "type": "geometry",
      "field": "isoline_tomtom",
      "fieldfx": "ST_AsGeoJSON(isoline_tomtom)",
              "edit": {
              "meta": "isoline_tomtom_meta",
       "isoline_tomtom": {}
   }
},
```

An Example of this can be found on the [issues](https://geolytix.dev/issues?layers=Mapbox%20Base,Mapbox%20Label,Issue:%20451&locations=Issue:%20451!dev.uk_glx_sites!31&lat=50.11839999999998&lng=-5.5408&z=18) instance

**Comment by dbauszus-glx** [comment]
`hidden` is a v4 infoj entry key which will hide the element returned from the entry function in the location view if set.

We won't introduce this feature to v3.

We can either leave it as is. Whereas `hidden: true` will skip the processing of the infoj entry in the infoj method.

Or we remove the line to continue the loop if hidden is true for an entry.

As a bit of background. I introduced the option to continue as an entry produced an error exception when I tried to load a v4 configuration in a v3 instance. This should not happen.

We need to make sure that any configuration will be skipped if not understood but not cause the Mapp client process to keel.
