### ISSUE TITLE
Charts with nulled datasets

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#454]
At the moment we return 'no data available' message when query for the chart returns null.
The pitfall is that chart will not update when data is dynamically changed (eg. using a query parameter).
It will not update from non-empty datasets to null either.
Looks like the chart must be destroyed and recreated to work around it.

Possible solution?  

- display empty chart
- display empty chart with message 'no data...'
- hide target element?

I don't think we can get away with suppressing canvas element chartjs creates.

**Comment by cityremade** [comment]
https://codepen.io/cityremade/pen/OJOPEYr

**Comment by dbauszus-glx** [comment]
The setData() method for charts and tables has a check for noDataMask. If set and the data provided as argument to the setData() method is falsy a mask will be applied to the dataview  target.
