### ISSUE TITLE
Gazetteer Data sets restricted by roles

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#458]
**Problem**
Currently in a workspace you cannot restrict a gazetters dataset per user role. You have to make two separate locales and restrict them to a role to achieve this.

**Requested Solution**
Could we add the role object to a gazetteers dataset!

```
    "gazetteer": {
        "provider": "GOOGLE",
        "country": "GB",
        "placeholder": "eg. London",
        "label": true,
        "optional": true,
        "datasets": [
          {
            "layer": "LAYER",
            "table": "TABLE",
            "label": "LABEL",
            "roles": {
              "role_1": null
            }
          },
          {
            "layer": "LAYER_2",
            "table": "TABLE_2",
            "label": "LABEL_2",
            "roles": {
              "role_2": null
            }
          }]
      },
```

**Comment by dbauszus-glx** [comment]
The gazetteer module will get a location from the layer in the dataset configuration.

Roles should therefore be taken from the layer and not the dataset configuration in the gazetteer.

This is now enabled. https://github.com/GEOLYTIX/xyz/commit/6e9a1eba27ce4b6e0fd59fde0715cce62af6ec12
