### ISSUE TITLE
Grid colour bins

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#46]
The distribution is linear between min / avg / max. Not linear between min and max.

**Comment by dbauszus-glx** [comment]
The distribution of values into colour bins is now outlined in the developer documentation.

https://geolytix.gitbook.io/xyz-developer-guide/workspaces/layers/grid-hex-layer

It should be possible to select a different distributions such as natural breaks, standard deviation, etc.

**Comment by cityremade** [comment]
Closing as complete.
