### ISSUE TITLE
Indicator that a layer in the group is on

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#478]
I can no longer see if a layer within a closed group is on, it makes it hard to locate where the displayed layer panel is.
If we don't want the group to be toggled all at once a tiny indicator dot next to the group name would do.

<img width="313" alt="group panel dot" src="https://user-images.githubusercontent.com/7070711/179192792-b77fc89d-0440-4f0f-82ae-ec317bd449e9.png">

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/commit/9d6c62063d7e4b673d1ed9b4f9b86f448d2950be

The button will only be shown when a layer is displayed. The button will hide all layers.
