### ISSUE TITLE
Layer group toggle not hiding all layer tabs.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#486]
At times I am using layer.view to listen for a layer being toggled off - in v3 it used to be 'display-off' event.
I can't catch this event when I toggle a layer group off.

Possible solutions 
- ensure tabs belonging to each layer are hidden when layer is toggled from the group panel
- dispatch an event layer can listen for.

I prefer the first one.

**Comment by dbauszus-glx** [comment]
Layer and locations have callback arrays. These show and hide methods which are assigned in the decorator call these at the end of their execution.

https://github.com/GEOLYTIX/xyz/blob/v4/lib/layer/decorate.mjs

The layer view pushes a function to toggle the button status as well as remove tabs for the layers tabs array.

```
  layer.hideCallbacks.push(()=>{
    toggleDisplay.classList.remove("on")
    layer.tabs?.forEach(tab => tab.remove())
  })
```

You need to either add a tab to the tab array; recommended. Or you can push a method to hide your custom tab into the hideCallbacks array.

Likewise there is a showCallbacks array which will show tabs when the layer.display method is called.

```
  layer.showCallbacks.push(()=>{
    toggleDisplay.classList.add("on")
    layer.tabs?.forEach(tab => tab.display && tab.show && tab.show())
  })
```
