### ISSUE TITLE
Ensure that tabs are hidden or shown with layer

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#489]
layer.hide() method doesn't hide a tab added to the layer.tabs[] array.

**Comment by dbauszus-glx** [comment]
Should be fixed here. https://github.com/GEOLYTIX/xyz/commit/ad20bc3f18fce9ae9a308397d1eafebb33d629f2

The layer.tabs array has been removed. The tab/entry show() and hide() method calls are pushed into the layer show and hide callback arrays.
