### ISSUE TITLE
Option to hide panels

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#490]
Give option to hide elements from layer panel while keeping ability to control objects programatically.

**Comment by dbauszus-glx** [comment]
Option to hide dataview panel

https://github.com/GEOLYTIX/xyz/commit/336fb1dde42ecc5e2074f16130024ba953576456

**Comment by dbauszus-glx** [comment]
Option to hide style panel
https://github.com/GEOLYTIX/xyz/commit/0282d2d176c2da9e250c3315976a506df2b84096
