### ISSUE TITLE
Update Fastify to V2

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#50]

**Comment by dbauszus-glx** [comment]
I will do the upgrade at the end of the map control implementation as this will be a minor (instead of a patch) version increase.

**Comment by dbauszus-glx** [comment]
https://medium.com/@fastifyjs/fastify-v2-is-coming-to-town-ce279738bed6

**Comment by dbauszus-glx** [comment]
As of now. Fastify V2 is still a release candidate.

**Comment by dbauszus-glx** [comment]
Dun in v1.3+
