### ISSUE TITLE
Define geojson properties schema

### ISSUE THREAD

**Issue by MatheusAnciloto** [GEOLYTIX/xyz#501]
The layers/geojson endpoint has been modified to return properties provided as fields request parameter.

```
const fields = req.params.fields && Array.isArray(req.params.fields)?req.params.fields:[req.params.fields]

var q = `
 SELECT
  ${layer.qID || null} AS id,
  ${fields?fields.join(', ')+',':''}
  ST_asGeoJson(${layer.geom}) AS geomj
 FROM ${req.params.table || layer.table}
 WHERE true ${filter};`

res.send(rows.map(row => ({
 type: 'Feature',
 geometry: JSON.parse(row.geomj),
 id: row.id,
 properties: fields && fields.reduce((pojo, field)=>({...pojo, [field]:row[field]}),{}) || undefined
})))
```

**Comment by dbauszus-glx** [comment]
This should no longer be required. The properties schema for geojson requests can now be defined as properties in the JSON layer.

The bristol sentiment dataset defined in the dev workspace returns a location's sentiment as specified in the properties object.
