### ISSUE TITLE
Prevent an empty drawing panel in layer view

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#504]
Case:

layer where we allow only delete  - as creation may come from a custom plugin.
Can we prevent layer editing panel from being created if the only entry is delete: true?

At the moment it's created empty.

<img width="316" alt="Screenshot 2022-09-30 at 15 17 32" src="https://user-images.githubusercontent.com/7070711/193289952-092a514f-a42b-4c79-b662-2821563d1545.png">

**Comment by cityremade** [comment]
actually hiding the panel would work

**Comment by dbauszus-glx** [comment]
I made mistake to check whether cards array exist rather than checking the cards array length.

Should be fixed here.

https://github.com/GEOLYTIX/xyz/commit/7e94f801c9c9d09f6dc4e5cb15bf356e4f5f3350
