### ISSUE TITLE
Chart JS - include support for non-responsive and fixed-size charts.

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#505]
At the moment we can't set size to chart canvas: 
https://www.chartjs.org/docs/latest/configuration/responsive.html
https://www.chartjs.org/docs/latest/configuration/responsive.html#configuration-options

This results in charts displayed huge in tabview or very small when responsive flag is off.

I'd like to be able to use canvas size in tabview to prevent unwanted responsive scaling.

**Comment by dbauszus-glx** [comment]
A target element could be provided with implicit sizing.

Alternatively the parent element for the target can be implicitly sized.
