### ISSUE TITLE
Filter on a fieldfx doesn't seem to work

### ISSUE THREAD

**Issue by fazzer14** [GEOLYTIX/xyz#507]
doing something like the below

```js
{
  "field": "pop_density",
  "fieldfx": "round((pl_pop_total/(ST_AREA(geom_3857_1p)/1000000.0))::numeric,1)",
  "title": "Population Density (pop per sqkm)",
  "inline": true,
  "filter": {
    "type": "integer"
  }
}
```

doesn't open up the filter sliders of input boxes.

**Comment by dbauszus-glx** [comment]
The configuration is correct. A `type: integer` is shorthand for a `type: numeric` filter with the step set to 1, which is the default anyways.

I believe the query for the max and min values fails or times out which will a requirement for the filter card to be displayed.

You can set the min / max values in the filter config block. If set by user, no query for the min and max must be sent prior to constructing the card with the range elements.

```js
"filter": {
  "title": "range filter",
  "type": "numeric",
  "max": 10,
  "min": 5,
  "step": 1
}
```

**Comment by fazzer14** [comment]
the actual issue is you're using "field" in the max and minimum calculations rather than "fieldfx"

**Comment by dbauszus-glx** [comment]
Fieldfx cannot be used for the field_max.js module query.

The field is provided as a query parameter which must be escaped in order to be white listed against SQL injection.

```
module.exports = `
  SELECT
    max(\${field})
    FROM \${table}
    WHERE true \${filter};`
```
