### ISSUE TITLE
Fly to selected location

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#510]
The mvt layer I've worked with has both pin and geometry type entries.
When selected and using fly to location from the location panel the mapview zooms to the marker, not the extent of the polygon feature.

**Comment by dbauszus-glx** [comment]
I cannot reproduce this.

The geometry entry method pushes the OL layer into the Layers array of the location object.

https://github.com/GEOLYTIX/xyz/blob/v4/lib/ui/locations/entries/geometry.mjs#L165

The location.flyTo method will iterate through the Layers to determine the combined extent for the mapview view.

https://github.com/GEOLYTIX/xyz/blob/v4/lib/location/decorate.mjs#L125

**Comment by cityremade** [comment]
closing as it was clarified.
