### ISSUE TITLE
Modify interaction - handling multipolygons

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#513]
Editing features on layers with multipolygons causing these issues:

1) each click in the interaction displays save/cancel menu - probably aftermath of start/end point not linking
2) only the first feature in the multipolygon gets style with prominent points. Big radius point styling is needed as it makes it easier to move/delete vertices.

What do we do?

**Comment by dbauszus-glx** [comment]
This is a bug which should be resolved with this PR. https://github.com/GEOLYTIX/xyz/pull/536

We previously only checked whether linestrings have enough vertices to be valid.

I added a specific check for polygon type. Every other geometry is assumed to be a multigeometry.

Vertice styles are on a multipoint geometry which is returned from utils.verticeGeom. This method will now flatten multigeometry coordinate arrays.
