### ISSUE TITLE
S3 bucket integration

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#526]
It should be possible to upload data from the client directly into an S3 bucket.

If possible this should be done without the need to load the AWS SDK on the client side.

A preferred solution would be to pipe the post request through the /mapp/proxy endpoint.

If this isn't possible we should introduce an endpoint which provides a signed URL to the client for the upload.

**Comment by RobAndrewHurst** [comment]
Yeah also not a fan of using the SDK. Using the API's should be perfect!

**Comment by dbauszus-glx** [comment]
It must also be possible to load data from an S3 bucket to the browser and to pipe from the S3 bucket into a PostGIS table.

This is not possible with the Aurora Serverless v1 but v2. We need to test this with Aurora Serverless v2 as well as hosted PostgreSQL server.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.S3Import.html

**Comment by dbauszus-glx** [comment]
It should also be possible to store a workspace in an S3 bucket and accessing the workspace through the S3 provider.
