### ISSUE TITLE
Multigeom Save Dialog Tap out

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#551]
**Problem**
When editing a multigeom and I want to edit multiple vertex in one go, and the save dialog appears over a vertex I want to edit, I can't click out in order to carry on with the edit. 

**Solution**
You can click on another vertex, but would be better to click/tap on the map to remove the dialog.

**Tried Alternatives**
You can carry on the edit by hitting save, but then its additional 2 clicks to get back into editing. Feels unnecessary. 

**Video showcasing the issue**

https://user-images.githubusercontent.com/43169158/208068503-657aa03b-9b30-4303-9f94-6766395c986a.mov

**Comment by dbauszus-glx** [comment]
XYZ/Mapp doesn't support the drawing of multi-geometries. In order to address the editing of multi-geometries the drawing of multi-geometries must be implemented first.
