### ISSUE TITLE
Adding layer with restricted zoom levels in a custom view

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#555]
I noticed it while loading a layer with zoom dependent tables (layer.tables: {}) to a map in full extent.
Solution is needed for this case - I don't have clarity whether programatically loading a layer outside its permitted zoom levels should be allowed - should not crash in red though :)

**Comment by dbauszus-glx** [comment]
What is the actual error exception?

**Comment by dbauszus-glx** [comment]
Is it possible to see this in a codepen?
