### ISSUE TITLE
Plugins and Workspaces in public directory

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#570]
Public front end resources should be taken out of the XYZ repository and made available in a different public repository.

It shouldn't require a PR in this repository to change a plugin or workspace.

Development workspaces and all plugins should not be part of all deployments.

**Comment by RobAndrewHurst** [comment]
Will any plugins then remain as core?

**Comment by dbauszus-glx** [comment]
No.

**Comment by RobAndrewHurst** [comment]
Versioning is going to be the big problem here though.

Thoughts of tagging commits on the branch for plugins is good. 

Or multiple branches.

**Comment by dbauszus-glx** [comment]
An issue maybe, but not necessarily a problem. Let's say a PR breaks a plugin, or a change to the workspace causes an issue. Not great if they are both part of the same repository. Not a problem if the plugin is only loaded if needed.

At current there are 23 plugins in the public folder. I know that some of them do not work. Who checks every plugin on every PR? Will there be 30+ plugins in the future? 50? 100+?

Versioning is not a problem if there is nothing to version in the public directory. At current the plugin directory is unmaintainable hence this RFC.

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/583
