### ISSUE TITLE
Unify dropdown and dropdown_multi methods

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#606]
A multi select dropdown should be created by providing the multi flag to the dropdown element method.

Dropdown_multi should redirect to the updated dropdown method with a warning to change the method call.

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/636

**Comment by RobAndrewHurst** [comment]
Can this be closed?

**Comment by dbauszus-glx** [comment]
Yes. This has been implemented.
