### ISSUE TITLE
Default DBS param as fallback

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#619]
Queries and layer templates require a DBS param.

The DBS param can be set in the layer config in the workspace, or in the template.

The DBS can also be provided as param with a query. In this case the provided DBS param will overwrite any other specified DBS param.

A default param for either a locale or the workspace as a total could be introduced.

This would eliminate the need to specify the same DBS param multiple times in the workspace. The default param would be a fallback if no other param is specified. This can be overwritten either in the template, layer config, or queryparams.

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/644

**Comment by RobAndrewHurst** [comment]
Has this been included in docs? Can it be closed?

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/wiki/Workspaces#dbs
