### ISSUE TITLE
Gazetteer : Add Zoom flag

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#62]

**Comment by dbauszus-glx** [comment]
Currently the map zooms in on a location from 3rd party providers (Google, Mapbox) but not when an item is selected from a XYZ data source. The map should zoom to the location when an item is selected through the gazetteer.

**Comment by dbauszus-glx** [comment]
The gazetteer select will now call the locations flyto method.

**Comment by dbauszus-glx** [comment]
The zoom flag can be set in the gazetteer configuration.
