### ISSUE TITLE
Add release version in metadata for deployments

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#69]
As we will have different instances on different versions it would be great to be able to display the version number somehow to allow us to be certain which version is being used if clients or the team discover bugs.

**Comment by dbauszus-glx** [comment]
Attribution will can now be set on a locale allowing to specify what should be shown in the map control attribution.

This allows to set the XYZ attribution to include a version in the link text. The link itself can also use branch and or commit specifier.

![image](https://user-images.githubusercontent.com/22201617/52210210-3adc0980-287e-11e9-9ccb-3bb8fc358c76.png)
