### ISSUE TITLE
Images for project outline

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#70]
Just images

**Comment by cityremade** [comment]
![1420749611735974840](https://user-images.githubusercontent.com/7070711/52349005-824ccc00-2a1d-11e9-94df-411e59f79a51.jpg)
![176577985419348995](https://user-images.githubusercontent.com/7070711/52349006-82e56280-2a1d-11e9-8e18-7c8fcc56a200.jpg)

**Comment by dbauszus-glx** [comment]
Will keep this open until a hosted solution has been found for concepts, tutorials, etc.
