### ISSUE TITLE
Can't zoom to selected point (cluster layer)

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#71]
![screenshot 2019-02-07 at 14 48 03](https://user-images.githubusercontent.com/7070711/52419161-79c0c800-2ae7-11e9-9a5c-ec4f302395d8.png)
The problem is flyToBounds on point feature in zoom.mjs:
![screenshot 2019-02-07 at 14 49 06](https://user-images.githubusercontent.com/7070711/52419201-8c3b0180-2ae7-11e9-9d62-2bffbd8eb4d9.png)

**Comment by dbauszus-glx** [comment]
This should be fixed in the current tablecontrol branch.
