### ISSUE TITLE
Gitbooks

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#73]
We may have to rethink the use of gitbooks. There is a plugin for iframes to run on gitbooks pages but I could not make this work.

The ideal solution will be github page (probably a Gatsby application) with a theme that allows javascript code execution and other iframes.

**Comment by dbauszus-glx** [comment]
There is an impressive [site showcase](https://www.gatsbyjs.org/showcase/) on the Gatsby site.

The ghost docs template seems to tick most boxes. https://github.com/TryGhost/docs

[https://docs.ghost.org/](https://docs.ghost.org)

**Comment by cityremade** [comment]
Gitbooks no longer in use.
