### ISSUE TITLE
Create point from device location

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#76]
Make point from navigator location.

**Comment by dbauszus-glx** [comment]
Thinking about this... That should be a 1hr job.

With the migration to the module (map, table, view) control structure the locate method is always available.

A method need to be added to this module to just return the lat lon of the location not toggle the display of the locator icon.

Then a new method needs to be added to draw. Whereas point asks for lat lon from map click the new method would ask for lat lon from locator and put the new location on map.

Done.

**Comment by dbauszus-glx** [comment]
I added a locator draw method. https://github.com/GEOLYTIX/xyz/commit/d77ef07913171aff07555e28426a24daff22c1ea

In the edit block add `locator:true`. The 'Current Position' button will generate a point location on the current location as retrieved from the navigator API.
