### ISSUE TITLE
Layer & Location Tables

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#77]
The tableview control consist of following components.

**create** - Method to create a tableview container with tab_bar, buttons and resize events.
**addTab** - Method which adds a tab to the tab_bar for table. Fires table.activate event when clicked.
**removeTab** - Method to remove a tab from tab_bar. Activates last table in tables array or hides tableview container is tables array length is 0 after splicing.
**layerTable** - Method to create a layerTable.

_node_ - Tableview container element.
_height_ - Table height, default 'calc(100% - 55px)'
_tables_ - Array which holds all table objects.
_current_table_ - The current table object.
_resize_bar_ - Div element on top of nav_bar used to resize tableview container.
_nav_bar_ - Div element (nav) which holds ul/li tab elements.
_btn_ - Object which holds the tableview buttons if assigned.

Layer tables are defined in the tableview definition in a layer. A layer can have multiple table definitions.

Example from dev.json
```
"tableview": {
  "tables": {
      "table1": {
          "title": "Population / GDP",
          "display": true,
          "columns": [
              {
                  "field": "name",
                  "type": "text"
              },
              {
                  "title": "Population Est",
                  "field": "pop_est",
                  "type": "integer"
              },
              {
                  "field": "gdp_md_est",
                  "type": "integer"
              }
          ]
      },
      "GDP / Population": {
          "display": true,
          "columns": [
              {
                  "field": "name",
                  "type": "text"
              },
              {
                  "field": "gdp_md_est",
                  "type": "integer",
                  "postfix": " dollars"
              },
              {
                  "title": "Population Est",
                  "field": "pop_est",
                  "type": "integer"
              }
          ]
      }
  }
}
```

The table object itself which is generated by the tableview.layerTable method has following entries.

**Tabulator** - The Tabulator object generated with the [Tabulator library](http://tabulator.info/) (utils.Tabulator).
**columns** - Array of table columns.
**activate** - Method which makes the table the current_table of the tableview module.
**update** - Updates the table data from XYZ host.

Please keep this issue open until fully tested and documented.

This should be tested fully after the location tables are implemented.

**Comment by dbauszus-glx** [comment]
Tables are put into the _xyz.tableview.tables[] array.

Removing a table will make the next table active.

If no tables are in array the tableview will not be displayed.

Layer show and remove events take care whether tables should be shown according to their display property.

Location tables update when the view updates.

The display property on a location table defines whether a table should be shown by default when the location is selected.

A layer table can be called like so from the xyz control:

```
  _xyz.tableview.layerTable({
    layer: _xyz.layers.list.COUNTRIES,
    key: 'GDP / Population',
    target: document.getElementById('xyz_table1')
  });
```

A location table can be called like so from the control:

```
  _xyz.tableview.locationTable({
    title: 'Age Profile',
    location: {
      layer: 'report_test',
      id: 41
    },
    target: document.getElementById('xyz_table1')
  });
```

**Comment by cityremade** [comment]
Closing as totally outdated.
