### ISSUE TITLE
Change the decimal to a percentage under the demographics bar

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#79]
Two clients have asked for the decimal to be changed to a percentage under the demographics bar (see image)

age_profile_uk_total*(100*age_18to24_15min/total_age_15min)/age_profile_uk_18to24

![demog bar](https://user-images.githubusercontent.com/46957630/52722526-aff8be80-2fa3-11e9-8914-1f909a491d34.GIF)

**Comment by dbauszus-glx** [comment]
Will be in next release.

![image](https://user-images.githubusercontent.com/22201617/53413151-242f5b00-39c3-11e9-9e0a-df35f572dba2.png)
