### ISSUE TITLE
Openlayers layer changed method unavailable for gazetteer locations

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#799]
**Describe the bug**
After Selecting a location (dataset) from the gazetteer, the property length is undefined in the wkt.mjs
After Selecting a location (MAPBOX) from the gazetteer, the property changed is undefined in the pin.mjs
**To Reproduce**

Use the bugs and testing launcher

1. Go to the Gazetteer, give any input
2. Click on an entry coming from a dataset, and this will result in the error

![image](https://github.com/GEOLYTIX/xyz/assets/43169158/3bc1aed9-fc54-49de-b1a7-db48b329acb9)

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/commit/8587dc138501ceb7250197e8cace636a35c01907 fix for pin issue

**Comment by dbauszus-glx** [comment]
Issue was caused by pin trying to restyle a layer without display. https://github.com/GEOLYTIX/xyz/commit/9747d048fe1d9dd89883a35c266703a6050edc8d
