### ISSUE TITLE
Zoom to location - look for additional geometries

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#80]
When we zoom to a location it sometimes feels like it goes too close, especially when a catchment is also displayed.  Can we loop through geometries and see what is sensible to display

**Comment by dbauszus-glx** [comment]
This is now implemented with the locations branch to be merged this week.

**Comment by dbauszus-glx** [comment]
The flyTo method will also be called when a new catchment is generated.
