### ISSUE TITLE
Scrollbar not appearing on first load of a tabview table

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#805]
**Describe the bug**

**To Reproduce**
if you have a layer with a display true tabview table
the first time you load that layer and the table turns on
the table won't load a scrollbar even if one is required
if you then turn the layer off and back on - a scrollbar will occur

**Comment by dbauszus-glx** [comment]
This appears to have been fixed in this PR. https://github.com/GEOLYTIX/xyz/pull/807
