### ISSUE TITLE
MVT Clone Persists on Mapview after Editing Infoj Fields

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#806]
**Describe the bug**
With  `type: mvt_clone` entry in an `infoj`, with any entry in that `infoj` editable. 
When you press the save edits button, the `type: mvt_clone` is stored to the mapview and persists on the mapview, the only way to remove it is to refresh the page. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use any layer.json file that has a `type: mvt_clone` and an editable field. 
2. Turn on the `type: mvt_clone` for display on the mapview.
3. Edit the editable field.
4. Press save to store the edit.
5. Toggle the checkbox for the `type: mvt_clone`, clear locations, turn off the whole layer - the `type: mvt_clone` will remain on the mapview. 
6. Refresh the page and the `type: mvt_clone` will be removed.

**Expected behavior**
When any entry in the `infoj` is edited, the mvt_clone should be removed from the mapview and re-drawn (if set to display: true) after the update method. Otherwise, the mvt_clone would simply be turned off and removed (re-loading the `infoj` in its initial configuration state).

**Additional context**
I tried to solve this within the lib/location/decorate.mjs file on line 50 adding this code (which seems to work within a plugin for me but not here). 
``` js 
// If there's any infoj entries of type 'mvt_clone', remove from the map prior to updating.
  this.infoj.filter(entry => entry.type === 'mvt_clone').forEach(entry => {
    entry.mapview.Map.removeLayer(entry.L)
    entry.Layer.clones.delete(entry.L)
  });
```

**Comment by dbauszus-glx** [comment]
The MVT clone entry wasn't designed to cope with reloads. I will fix this.
