### ISSUE TITLE
When Editing Controlled by Roles Used - Editing Spanner Remains

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#812]
**Describe the bug**
When using editing controlled via roles, and merging the infoj entry keys and values based on the role.
If a user has no role, they are unable to edit any infoj entries which is correct.
But, the editing spanner appear on the location toolbar and allows them to toggle 'edit' mode - even though nothing happens.

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/818
