### ISSUE TITLE
Defaults method store user and date

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#828]
**Is your feature request related to a problem? Please describe.**
To remove the need for database-side triggers, it should be possible to store the user and the date via the `defaults` object in the `draw` method. 

**Describe the solution you'd like**
The defaults object should allow for date and user to be stored. 
``` json 
"defaults": { 
"field": "user",
"date_field": "date" 
} 
```
This would store the user to the `field` and the date to the `date_field` on the db.

**Comment by dbauszus-glx** [comment]
This can be achieved with a plugin that when loaded assigns the defaults for the fields in the plugin config.

```js
export default (function () {

    mapp.plugins.draw_defaults = layer => {

        Object.entries(layer.draw_defaults).forEach(entry => {

            layer.draw.defaults ??= {}

            // Assign the user email as default.
            if (entry[0] === 'user') {

                layer.draw.defaults[entry[1]] = mapp.user?.email
            }

            // Assign the date as default.
            if (entry[0] === 'date') {

                layer.draw.defaults[entry[1]] = parseInt(Date.now() / 1000)
            }

            // Assign the datetime as default
            if (entry[0] === 'datetime') {

                layer.draw.defaults[entry[1]] = Date.now()
            }
        })
    }

})()
```
