### ISSUE TITLE
Undefined snap Property After Polygon Re-edit in geometry.mjs

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#928]
**Undefined snap Property After Polygon Re-edit in geometry.mjs**
After modifying a polygon, attempting to re-edit it results in the `snap` property on the `entry.edit` object in the `geometry.mjs` module being undefined.

**To Reproduce**
1. Modify a polygon.
2. Attempt to re-edit the modified polygon.
3. Check the `snap` property on the `entry.edit` object in the `geometry.mjs` module.
4. See that the property is `undefined`.

**Expected behavior**
The `snap` property on the `entry.edit` object in the `geometry.mjs` module should retain its value and not become `undefined` after modifying and re-editing a polygon.

**Screenshots/video**

https://github.com/GEOLYTIX/xyz/assets/43169158/19e6bffb-d91d-453b-b298-fa98c369a46b

**Additional context**
After refreshing the browser the modify button disappears and you can not longer edit a geometry.

**Comment by dbauszus-glx** [comment]
This was most likely caused by an inconsistency in the update method whereas the edit control was executed after the location view was rebuild.
