### ISSUE TITLE
Deployment to Zeit doesn't work on their v2 platform

### ISSUE THREAD

**Issue by stev-0** [GEOLYTIX/xyz#93]
At the moment the docs are out of sync as I don't believe this is possible, and Zeit are now enforcing new users onto the v2 platform, so the zeroo configuration promise is not fulfilled

**Comment by dbauszus-glx** [comment]
That is correct. Zeit Now v2 is actually a misnomer which creates some annoyance in the Zeit community. XYZ can only be deployed via Zeit Now v1. To deploy from github via the Zeit Now CLI you need to specify the version.

```
now -V 1 GEOLYTIX/geolytix -e DIR="/dev" -e ...
```

Unfortunately if you signed up with Zeit after January you will not get access to v1 at all. This is very annoying. We are currently putting together workshop documentation which will show how to deploy to AWS Lambda.

As for Zeit v2 this is using an API gateway which is fundamentally different to deploying XYZ as a cloud function (lambda). We have no current plans to support Zeit v2 as we do not want to get vendor locked. In the case that Zeit retired v1 we would probably migrate our own infrastructure to AWS or Google App Engine. We plan to have workshops for each of the cloud providers ready soon.

**Comment by abdelhameedhamdy** [comment]
Hi,

when trying deploying with -V 1, it throws the following error .. 

 now -V 1 GEOLYTIX/geolytix -e DIR="/dev"
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Didn't find directory. Searching on GitHub...
> Deploying GitHub repository "GEOLYTIX/geolytix" under ....
> Using project geolytix
> Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade

**Comment by dbauszus-glx** [comment]
Unfortunately the warnings are nonsense... Zeit Now v2 is a different product to v1 which is why a lot of people in the community are not happy about the wording or planning from the Zeit team.

See https://spectrum.chat/zeit/now/thoughts-on-why-now-2-0-is-kinda-disappointing~cbad7540-8159-41a7-9767-9c3f6310b497

Which version of the Zeit Now cli do you have installed? I know that there have been problems with versions around 10. I just upgraded to the latest version (14.2.3) and run a test deploy from the master branch defining only the DIR environment. I noticed that [zero configs are currently broken](https://github.com/GEOLYTIX/xyz/issues/94) but the issue should be fixed within the next hour or so.

![image](https://user-images.githubusercontent.com/22201617/54926744-d0a02680-4f08-11e9-8324-45a4054d5a02.png)

When did you create your Zeit account? If you created the account after 1 January you will never be able to use Zeit Now v1 as outlined [here](https://spectrum.chat/zeit/now/deploy-v1~5d1def00-3504-4618-9ef4-40d64e69f573).

**Comment by dbauszus-glx** [comment]
I just realised that earlier I wrote GEOLYTIX/geolytix which is the repository for our website on which I am currently working. My bad. The repo for XYZ is of course GEOLYTIX/xyz.

**Comment by abdelhameedhamdy** [comment]
> Unfortunately the warnings are nonsense... Zeit Now v2 is a different product to v1 which is why a lot of people in the community are not happy about the wording or planning from the Zeit team.
> 
> See https://spectrum.chat/zeit/now/thoughts-on-why-now-2-0-is-kinda-disappointing~cbad7540-8159-41a7-9767-9c3f6310b497
> 
> Which version of the Zeit Now cli do you have installed? I know that there have been problems with versions around 10. I just upgraded to the latest version (14.2.3) and run a test deploy from the master branch defining only the DIR environment. I noticed that [zero configs are currently broken](https://github.com/GEOLYTIX/xyz/issues/94) but the issue should be fixed within the next hour or so.
> 
> ![image](https://user-images.githubusercontent.com/22201617/54926744-d0a02680-4f08-11e9-8324-45a4054d5a02.png)
> 
> When did you create your Zeit account? If you created the account after 1 January you will never be able to use Zeit Now v1 as outlined [here](https://spectrum.chat/zeit/now/deploy-v1~5d1def00-3504-4618-9ef4-40d64e69f573).

My Zeit account created after Jan 2019 
Ziet Now cli version is 14.2.3

**Comment by abdelhameedhamdy** [comment]
So, new Zeit Now accounts will not be to deploy xyz anymore, right !

**Comment by dbauszus-glx** [comment]
That's right. We got caught out by this ourselves and hope to provide better step by step guides soon.

@RobAndrewHurst has already done a test deployment to Amazon AWS. I would like to test the [serverless.com](https://serverless.com/) framework which shows great potential. We hope to have our documentation with guidelines moved to github pages before the summer.

**Comment by dbauszus-glx** [comment]
It should work using the [@now/node-server](https://zeit.co/docs/v2/deployments/official-builders/node-js-server-now-node-server/) builder.

I hope to run a test next week and will provide a guide if successful.

**Comment by dbauszus-glx** [comment]
Quick update from my end... The node-server didn't work smoothly and will require significant changes to the server.js application script. @RobAndrewHurst has successfully deployed to AWS though and we will post documentation in this regard soon.

**Comment by dbauszus-glx** [comment]
Deployments do now work with Vercel (former Zeit). In fact the v1 platform is no longer available.
