### ISSUE TITLE
Gazetteer wildcard query error;

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#945]
Gazetteer with default wildcard parameter and several datasets to search.
I typed in asterisk by mistake `W*` and it blew up the "gaz query".
Found on branch main;

```
q: '\n' +
    '  SELECT \n' +
    '   AS label,\n' +
    '  id AS id\n' +
    '  FROM table\n' +
    '  WHERE ::text ILIKE $1\n' +
    '   \n' +
    '      \n' +
    '      \n' +
    '  LIMIT 10;',
  arr: [ 'w1%' ]
}
{
  err: error: syntax error at or near "AS"
```

<img width="262" alt="Screenshot 2023-10-03 at 16 00 04" src="https://github.com/GEOLYTIX/xyz/assets/7070711/bd0bb109-225d-4dba-9bbe-761097c610b1">

**Comment by dbauszus-glx** [comment]
What is the error message? I don't think this is related to the wildcard. Providing additional wildcards shouldn't do anything.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/c95149b1-3599-4ac5-a6cf-aacb2625e78b)
