### ISSUE TITLE
Missing legend on hex grid layer

### ISSUE THREAD

**Issue by lisataylor-geolytix** [GEOLYTIX/xyz#95]
Might be in the config rather than an issue (if so just let me know) but the legend seems to have disappeared on hex grid layers in v1.4.0

![Hex legend issue](https://user-images.githubusercontent.com/46957630/54952757-a4070180-4f3e-11e9-9032-1afb4db1232f.JPG)

**Comment by dbauszus-glx** [comment]
On which instance is that for me to check?

**Comment by lisataylor-geolytix** [comment]
Rob has fixed this already!  It was on Richer Sounds and anything else on v1.4.0 at the time

**Comment by dbauszus-glx** [comment]
@RobAndrewHurst Can you add a note on the issue/fix and close?

**Comment by RobAndrewHurst** [comment]
`if(!layer.style.theme && layer.format != 'grid') return;`

Added in additional logic to exclude 'grids' from the return statement, where a layer did not have a theme
