### ISSUE TITLE
Opacity on filtered text in Firefox

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#96]
Using a the legend filter for categorized themes works but the filtered text which get's an opacity of .5 is cannot be seen in Firefox.

![image](https://user-images.githubusercontent.com/22201617/55067980-a8cfd080-5078-11e9-8243-3a2b6a1378dc.png)

Left side Chrome, right side Firefox. The same filter being applied.

**Comment by cityremade** [comment]
Done. fillOpacity is set along with opacity.
